# Generated by Django 5.2.12 on 2026-04-04 18:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0013_remove_entryorderconfig_capital_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('send_time', models.TimeField(default=datetime.time(18, 0))),
                ('include_pnl', models.BooleanField(default=True)),
                ('include_trades', models.BooleanField(default=True)),
                ('include_insights', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summary_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_summary_schedule',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('TRADE_EXECUTED', 'Trade Executed'), ('SL_HIT', 'Stop Loss Hit'), ('TARGET_HIT', 'Target Hit'), ('STRATEGY_PAUSED', 'Strategy Paused'), ('STRATEGY_ERROR', 'Strategy Error'), ('RISK_ALERT', 'Risk Alert'), ('DAILY_SUMMARY', 'Daily Summary')], max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('TRADE_EXECUTED', 'Trade Executed'), ('SL_HIT', 'Stop Loss Hit'), ('TARGET_HIT', 'Target Hit'), ('STRATEGY_PAUSED', 'Strategy Paused'), ('STRATEGY_ERROR', 'Strategy Error'), ('RISK_ALERT', 'Risk Alert'), ('DAILY_SUMMARY', 'Daily Summary')], max_length=40)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=80)),
                ('push_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preference',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
