# Generated by Django 5.2.12 on 2026-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TRADE_EXECUTED', 'Trade Executed'), ('SL_HIT', 'Stop Loss Hit'), ('TARGET_HIT', 'Target Hit'), ('STRATEGY_PAUSED', 'Strategy Paused'), ('STRATEGY_ERROR', 'Strategy Error'), ('RISK_ALERT', 'Risk Alert'), ('DAILY_SUMMARY', 'Daily Summary'), ('COMMUNITY_REPLY', 'Community Reply'), ('COMMUNITY_MENTION', 'Community Mention'), ('COMMUNITY_FOLLOW', 'Community Follow'), ('BADGE_UNLOCKED', 'Badge Unlocked'), ('STREAK_WARNING', 'Streak Warning'), ('CHALLENGE_PROGRESS', 'Challenge Progress'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('PROOF_VERIFIED', 'Proof Verified'), ('MODERATION_ALERT', 'Moderation Alert')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('TRADE_EXECUTED', 'Trade Executed'), ('SL_HIT', 'Stop Loss Hit'), ('TARGET_HIT', 'Target Hit'), ('STRATEGY_PAUSED', 'Strategy Paused'), ('STRATEGY_ERROR', 'Strategy Error'), ('RISK_ALERT', 'Risk Alert'), ('DAILY_SUMMARY', 'Daily Summary'), ('COMMUNITY_REPLY', 'Community Reply'), ('COMMUNITY_MENTION', 'Community Mention'), ('COMMUNITY_FOLLOW', 'Community Follow'), ('BADGE_UNLOCKED', 'Badge Unlocked'), ('STREAK_WARNING', 'Streak Warning'), ('CHALLENGE_PROGRESS', 'Challenge Progress'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('PROOF_VERIFIED', 'Proof Verified'), ('MODERATION_ALERT', 'Moderation Alert')], max_length=40),
        ),
    ]
