version: '3.8'

services:
  local-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=quantnest
      - POSTGRES_PASSWORD=quantnest
      - POSTGRES_DB=quantnest_dev
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=local-secret-key
      - DEBUG=True
      - DATABASE_URL=postgres://quantnest:quantnest@local-db:5432/quantnest_dev
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - local-db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data: