# Generated by Django 5.2.12 on 2026-05-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0005_add_optimization_error_and_mc_distribution'),
        ('strategies', '0015_alter_entryorderconfig_entry_price_logic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('flag_type', models.CharField(choices=[('SPAM', 'Spam'), ('FAKE_PNL', 'Fake PnL'), ('ABUSE', 'Abuse'), ('PUMP_DUMP', 'Pump And Dump'), ('REFERRAL_SPAM', 'Referral Spam'), ('SUSPICIOUS_PROMOTION', 'Suspicious Promotion')], max_length=40)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_moderation_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_ai_moderation_flag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_accepting_sessions', models.BooleanField(default=False)),
                ('verified_mentor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_mentor_profile',
            },
        ),
        migrations.CreateModel(
            name='OfficeHourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='reputation.mentorprofile')),
            ],
            options={
                'db_table': 'reputation_office_hour_session',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reputation.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_bookings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='reputation.officehoursession')),
            ],
            options={
                'db_table': 'reputation_mentorship_booking',
            },
        ),
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_type', models.CharField(max_length=80)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_score',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('chart_state_json', models.JSONField(blank=True, default=dict)),
                ('indicator_state', models.JSONField(blank=True, default=dict)),
                ('drawing_state', models.JSONField(blank=True, default=dict)),
                ('candles_snapshot', models.JSONField(blank=True, default=list)),
                ('execution_markers', models.JSONField(blank=True, default=list)),
                ('journal_context', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=20)),
                ('is_immutable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_replays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_trade_replay',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraderReputationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credibility_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discipline_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('transparency_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sample_size_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('journal_honesty_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('strategy_survival_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('drawdown_discipline_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rule_follow_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('manipulation_flags', models.JSONField(blank=True, default=list)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_trader_profile',
                'ordering': ['-credibility_score'],
            },
        ),
        migrations.CreateModel(
            name='BacktestProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reproducibility_hash', models.CharField(max_length=128)),
                ('parameters_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='backtesting.backtestrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_backtest_proof',
                'unique_together': {('backtest_run', 'reproducibility_hash')},
            },
        ),
        migrations.CreateModel(
            name='StrategyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_type', models.CharField(choices=[('BACKTEST_REPRODUCIBLE', 'Backtest Reproducible'), ('STRATEGY_EXECUTION_VERIFIED', 'Strategy Execution Verified'), ('TRANSPARENCY_VERIFIED', 'Transparency Verified')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('transparency_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_strategy_verification',
                'unique_together': {('strategy', 'verification_type')},
            },
        ),
        migrations.CreateModel(
            name='TradingProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof_type', models.CharField(choices=[('BROKER_VERIFIED', 'Broker Verified'), ('PAPER_VERIFIED', 'Paper Verified'), ('TIMESTAMP_VERIFIED', 'Timestamp Verified')], max_length=40)),
                ('source_model', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('verification_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_trading_proof',
                'ordering': ['-created_at'],
                'unique_together': {('proof_type', 'source_model', 'source_id')},
            },
        ),
    ]
