# Generated by Django 5.2.12 on 2026-06-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperorder',
            name='slippage_applied',
        ),
        migrations.RemoveField(
            model_name='papertrade',
            name='slippage',
        ),
    ]
