# Generated by Django 5.2.12 on 2026-06-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0002_remove_paperorder_slippage_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyperformance',
            name='brokerage_paid',
        ),
        migrations.RemoveField(
            model_name='dailyperformance',
            name='taxes_paid',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='paperposition',
            name='unrealized_pnl_pct',
        ),
        migrations.RemoveField(
            model_name='papertrade',
            name='brokerage',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='broker_synced',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='last_broker_sync',
        ),
    ]
