# Generated by Django 5.2.12 on 2026-07-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0003_remove_dailyperformance_brokerage_paid_and_more'),
        ('strategies', '0017_remove_entryorderconfig_entry_price_logic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalallocation',
            name='deployed_version',
            field=models.ForeignKey(blank=True, help_text='Pinned strategy version for this paper allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_allocations', to='strategies.strategyversion'),
        ),
    ]
