# Generated by Django 5.2.12 on 2026-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0004_add_deployed_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalallocation',
            name='include_charges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='charges_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
