# Generated by Django 5.2.12 on 2026-08-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0005_add_charges_fields'),
        ('strategies', '0018_alter_strategy_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalallocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='capitalallocation',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_allocations', to='strategies.strategy'),
        ),
        migrations.CreateModel(
            name='PaperTradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='PAUSED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('trades_count', models.PositiveIntegerField(default=0)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='paper_trading.paperaccount')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_sessions', to='paper_trading.capitalallocation')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_sessions', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_trading_session',
                'ordering': ['-updated_at'],
            },
        ),
    ]
