# Generated by Django 5.2.12 on 2026-08-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0006_remove_capitalallocation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyperformance',
            name='brokerage_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dailyperformance',
            name='taxes_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
