# Generated by Django 5.2.12 on 2026-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0007_dailyperformance_brokerage_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='brokerage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
