# Generated by Django 5.2.12 on 2026-08-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0008_papertrade_brokerage_papertrade_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalallocation',
            name='today_pnl',
        ),
        migrations.RemoveField(
            model_name='capitalallocation',
            name='total_pnl',
        ),
        migrations.RemoveField(
            model_name='capitalallocation',
            name='utilized_amount',
        ),
        migrations.RemoveField(
            model_name='dailyperformance',
            name='avg_exposure',
        ),
        migrations.RemoveField(
            model_name='dailyperformance',
            name='max_exposure',
        ),
        migrations.RemoveField(
            model_name='dailyperformance',
            name='realized_pnl',
        ),
        migrations.RemoveField(
            model_name='dailyperformance',
            name='unrealized_pnl',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='margin_available',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='margin_used',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='realized_pnl',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='today_pnl',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='today_trades',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='total_pnl',
        ),
        migrations.RemoveField(
            model_name='paperaccount',
            name='unrealized_pnl',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='trades_count',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='invested_value',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='realized_pnl',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='today_pnl',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='today_trades',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='unrealized_pnl',
        ),
        migrations.DeleteModel(
            name='ExposureSnapshot',
        ),
    ]
