# Generated by Django 5.2.12 on 2026-08-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0009_remove_capitalallocation_today_pnl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalallocation',
            name='include_charges',
        ),
    ]
