# Generated by Django 5.2.12 on 2026-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_alter_instrument_exchange'),
        ('paper_trading', '0013_paper_session_execution_costs'),
        ('strategies', '0023_alter_strategy_visibility'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['account', '-exit_time'], name='paper_close_time_idx'),
        ),
    ]
