# Generated by Django 5.2.12 on 2026-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0014_papertrade_paper_close_time_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertradingsession',
            name='auto_disable_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
