# Generated by Django 5.2.12 on 2026-10-03 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0022_alter_strategy_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('mode', models.CharField(choices=[('RESEARCH', 'Research'), ('SCREEN', 'Screen')], max_length=10)),
                ('prompt', models.TextField(blank=True)),
                ('request', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('progress_message', models.CharField(default='Queued for research', max_length=255)),
                ('evidence', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('as_of', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='research.researchsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'request_id'), name='research_request_unique'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING'])), fields=('user',), name='research_one_active_run')],
            },
        ),
    ]
