# Generated by Django 5.2.12 on 2026-10-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_remove_old_ai_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrun',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchrun',
            name='tool_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='kind',
            field=models.CharField(choices=[('CHAT', 'Conversation'), ('SCREEN', 'Saved screen')], default='CHAT', max_length=12),
        ),
        migrations.CreateModel(
            name='ResearchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CREATE_DRAFT', 'Create strategy draft'), ('ADD_TO_WATCHLIST', 'Add to terminal watchlist'), ('START_BACKTEST', 'Start backtest')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROPOSED', 'Awaiting confirmation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROPOSED', max_length=12)),
                ('resource_ids', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='research.researchrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
