# Generated by Django 5.2.12 on 2026-05-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0015_alter_entryorderconfig_entry_price_logic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('TRADE_COMPLETED', 'Trade Completed'), ('JOURNAL_CREATED', 'Journal Created'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('LESSON_COMPLETED', 'Lesson Completed'), ('BACKTEST_FINISHED', 'Backtest Finished'), ('POST_CREATED', 'Post Created'), ('STRATEGY_DEPLOYED', 'Strategy Deployed'), ('RISK_RULE_BROKEN', 'Risk Rule Broken'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'), ('PROOF_VERIFIED', 'Proof Verified'), ('CHALLENGE_PROGRESS', 'Challenge Progress')], max_length=60)),
                ('source_app', models.CharField(blank=True, max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_domain_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('POST_CREATED', 'Post Created'), ('FOLLOWED_USER', 'Followed User'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'), ('COURSE_COMPLETED', 'Course Completed'), ('LESSON_COMPLETED', 'Lesson Completed'), ('STRATEGY_DEPLOYED', 'Strategy Deployed'), ('VERIFIED_TRADE', 'Verified Trade'), ('MARKETPLACE_MILESTONE', 'Marketplace Milestone'), ('CHALLENGE_PROGRESS', 'Challenge Progress'), ('REPLAY_SHARED', 'Replay Shared')], max_length=60)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('topic_slug', models.CharField(blank=True, max_length=80)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('domain_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_items', to='platform_events.domainevent')),
            ],
            options={
                'db_table': 'platform_activity_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['event_type', 'created_at'], name='platform_do_event_t_f6ec00_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['user', 'created_at'], name='platform_do_user_id_541b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['status', 'created_at'], name='platform_do_status_b1d813_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['activity_type', 'created_at'], name='platform_ac_activit_efb3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', 'created_at'], name='platform_ac_user_id_de63d5_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['topic_slug', 'created_at'], name='platform_ac_topic_s_c59096_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['visibility', 'created_at'], name='platform_ac_visibil_37161e_idx'),
        ),
    ]
