# Generated by Django 5.2.5 on 2026-03-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
        ('strategies', '0013_remove_entryorderconfig_capital_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestmetrics',
            name='max_consecutive_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtestmetrics',
            name='max_consecutive_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Strategy parameters used for this run.'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='risk_profile_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of the user's risk profile at the time of the run."),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_version',
            field=models.ForeignKey(blank=True, help_text='The specific strategy version used for this backtest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to='strategies.strategyversion'),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='mae',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Maximum Adverse Excursion (Max paper loss during trade)', max_digits=12),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='mfe',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Maximum Favorable Excursion (Max paper profit during trade)', max_digits=12),
        ),
    ]
