# Generated by Django 5.2.5 on 2026-03-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_backtestmetrics_max_consecutive_losses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestrun',
            name='data_resolution',
        ),
    ]
