# Generated by Django 5.2.5 on 2026-03-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_remove_backtestrun_data_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestmetrics',
            name='avg_mae',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='backtestmetrics',
            name='avg_mfe',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='backtestmetrics',
            name='monthly_returns_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='backtestmetrics',
            name='trade_efficiency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
