# Generated by Django 5.2.12 on 2026-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0004_backtestmetrics_avg_mae_backtestmetrics_avg_mfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlorun',
            name='equity_distribution_json',
            field=models.JSONField(blank=True, default=list, help_text='Percentile-based equity distribution for histogram rendering.'),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
