# Generated by Django 5.2.12 on 2026-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0005_add_optimization_error_and_mc_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationrun',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='optimizationrun',
            name='user',
        ),
        migrations.DeleteModel(
            name='OptimizationResult',
        ),
        migrations.DeleteModel(
            name='OptimizationRun',
        ),
    ]
