# Generated by Django 5.2.12 on 2026-07-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0006_remove_optimizationrun_strategy_and_more'),
        ('brokers', '0004_add_broker_charge_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='charge_profile',
            field=models.ForeignKey(blank=True, help_text='Charge profile for realistic cost simulation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to='brokers.brokerchargeprofile'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='fill_model',
            field=models.CharField(choices=[('SIGNAL_CLOSE', 'Signal Close'), ('NEXT_OPEN', 'Next Open'), ('VWAP', 'VWAP')], default='NEXT_OPEN', help_text='Fill price model: SIGNAL_CLOSE (optimistic), NEXT_OPEN (realistic), VWAP (conservative)', max_length=20),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='include_charges',
            field=models.BooleanField(default=True, help_text='Whether to include realistic charges (STT, stamp duty, etc.) in PnL'),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='charges_json',
            field=models.JSONField(blank=True, default=dict, help_text='Itemized charge breakdown: {entry_charges: {...}, exit_charges: {...}, total_charges: N}'),
        ),
    ]
