# Generated by Django 5.2.12 on 2026-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0007_add_fill_model_charges_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestmetrics',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
