# Generated by Django 4.2 on 2026-09-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0008_add_charges_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestrun',
            name='fill_model',
        ),
    ]
