# Generated by Django 5.2.12 on 2026-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0012_backtest_metrics_and_config_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttrade',
            name='mae',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Maximum adverse excursion in account currency for the entry quantity.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='backtesttrade',
            name='mfe',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Maximum favorable excursion in account currency for the entry quantity.', max_digits=12),
        ),
    ]
