# Generated by Django 5.2.12 on 2026-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0017_monte_carlo_result_bounds_and_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
