# Generated by Django 5.2.5 on 2026-01-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_daily_loss_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily loss in rupees', max_digits=12, null=True)),
                ('max_daily_loss_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Maximum daily loss as % of capital', max_digits=5)),
                ('max_daily_trades', models.PositiveIntegerField(default=50, help_text='Maximum trades per day across all strategies')),
                ('max_open_positions', models.PositiveIntegerField(default=10, help_text='Maximum concurrent open positions')),
                ('max_exposure_percentage', models.DecimalField(decimal_places=2, default=80.0, help_text='Maximum portfolio exposure as % of capital', max_digits=5)),
                ('max_per_strategy_allocation', models.DecimalField(decimal_places=2, default=25.0, help_text='Maximum capital allocated to a single strategy', max_digits=5)),
                ('max_per_instrument_exposure', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum exposure to a single instrument', max_digits=5)),
                ('max_per_sector_exposure', models.DecimalField(decimal_places=2, default=30.0, help_text='Maximum exposure to a single sector', max_digits=5)),
                ('max_drawdown_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Maximum portfolio drawdown before halt', max_digits=5)),
                ('trailing_drawdown_reset', models.BooleanField(default=True, help_text='Reset drawdown counter on new high')),
                ('alert_on_breach', models.BooleanField(default=True)),
                ('halt_on_breach', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Risk Profile',
                'verbose_name_plural': 'Portfolio Risk Profiles',
                'db_table': 'risk_portfolio_profile',
            },
        ),
        migrations.CreateModel(
            name='PositionSizingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sizing_method', models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_BASED', 'Risk Based')], default='CAPITAL_BASED', max_length=20)),
                ('fixed_quantity', models.PositiveIntegerField(default=1)),
                ('fixed_lots', models.PositiveIntegerField(default=1)),
                ('capital_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of capital per trade', max_digits=5)),
                ('risk_per_trade_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed rupee amount to risk per trade', max_digits=12, null=True)),
                ('risk_per_trade_percentage', models.DecimalField(decimal_places=2, default=1.0, help_text='Percentage of capital to risk per trade', max_digits=5)),
                ('max_position_size', models.PositiveIntegerField(blank=True, help_text='Maximum quantity per position', null=True)),
                ('max_position_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum rupee value per position', max_digits=15, null=True)),
                ('allow_scaling', models.BooleanField(default=False)),
                ('scaling_levels', models.JSONField(blank=True, default=list, help_text='List of {percentage, trigger_pct} for pyramiding')),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_sizing_rule', to='strategies.strategy')),
            ],
            options={
                'verbose_name': 'Position Sizing Rule',
                'verbose_name_plural': 'Position Sizing Rules',
                'db_table': 'risk_position_sizing_rule',
            },
        ),
        migrations.CreateModel(
            name='RiskViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('POSITION_SIZE', 'Position Size Exceeded'), ('DAILY_LOSS', 'Daily Loss Limit'), ('EXPOSURE', 'Exposure Limit'), ('DRAWDOWN', 'Drawdown Limit'), ('CONSECUTIVE_LOSS', 'Consecutive Losses'), ('MAX_TRADES', 'Max Trades Reached'), ('HALT_TRIGGERED', 'Trading Halt Triggered')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('message', models.TextField()),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('actual_value', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('action_taken', models.CharField(choices=[('LOGGED', 'Logged Only'), ('NOTIFIED', 'Notification Sent'), ('BLOCKED', 'Trade Blocked'), ('HALTED', 'Trading Halted'), ('CLOSED', 'Positions Closed'), ('DISABLED', 'Strategy Disabled')], max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_violations', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Violation',
                'verbose_name_plural': 'Risk Violations',
                'db_table': 'risk_violation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyAutoDisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('CONSECUTIVE_LOSSES', 'Consecutive Losing Trades'), ('DAILY_LOSS', 'Daily Loss Threshold'), ('WEEKLY_LOSS', 'Weekly Loss Threshold'), ('MONTHLY_LOSS', 'Monthly Loss Threshold'), ('WIN_RATE_DROP', 'Win Rate Below Threshold'), ('DRAWDOWN', 'Drawdown Exceeded')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('threshold_count', models.PositiveIntegerField(default=0)),
                ('auto_reenable', models.BooleanField(default=False, help_text='Automatically re-enable after cooldown')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours before auto re-enable')),
                ('require_manual_review', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_disable_rules', to='strategies.strategy')),
            ],
            options={
                'verbose_name': 'Strategy Auto-Disable Rule',
                'verbose_name_plural': 'Strategy Auto-Disable Rules',
                'db_table': 'risk_strategy_auto_disable',
            },
        ),
        migrations.CreateModel(
            name='TradeHaltCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('LOSS_AMOUNT', 'Loss Amount'), ('LOSS_PERCENTAGE', 'Loss Percentage'), ('CONSECUTIVE_LOSSES', 'Consecutive Losses'), ('MAX_TRADES', 'Maximum Trades'), ('DRAWDOWN', 'Drawdown Threshold'), ('TIME_BASED', 'Time-Based'), ('VOLATILITY', 'High Volatility'), ('CUSTOM', 'Custom Condition')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('threshold_count', models.PositiveIntegerField(default=0)),
                ('halt_duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of halt in minutes (0 = until EOD)')),
                ('close_open_positions', models.BooleanField(default=False, help_text='Close all positions when halt triggered')),
                ('send_notification', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(blank=True, help_text='Leave blank for portfolio-wide halt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halt_conditions', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halt_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Halt Condition',
                'verbose_name_plural': 'Trade Halt Conditions',
                'db_table': 'risk_halt_condition',
            },
        ),
    ]
