# Generated by Django 5.2.5 on 2026-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionsizingrule',
            name='sizing_method',
            field=models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_FIXED', 'Risk Based (Fixed Amount)'), ('RISK_PERCENTAGE', 'Risk Based (% of Capital)')], default='CAPITAL_BASED', max_length=20),
        ),
    ]
