# Generated by Django 5.2.5 on 2026-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0002_alter_positionsizingrule_sizing_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioriskprofile',
            name='max_per_sector_exposure',
        ),
        migrations.AddField(
            model_name='positionsizingrule',
            name='max_daily_trades',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of trades per day for this strategy'),
        ),
        migrations.AddField(
            model_name='positionsizingrule',
            name='max_open_positions',
            field=models.PositiveIntegerField(default=5, help_text='Maximum concurrent open positions for this strategy'),
        ),
    ]
