# Generated by Django 5.2.5 on 2026-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0003_remove_portfolioriskprofile_max_per_sector_exposure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionsizingrule',
            name='capital_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Percentage of capital per trade', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='positionsizingrule',
            name='fixed_lots',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='positionsizingrule',
            name='fixed_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='positionsizingrule',
            name='risk_per_trade_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Percentage of capital to risk per trade', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='strategyautodisable',
            name='threshold_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategyautodisable',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tradehaltcondition',
            name='threshold_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tradehaltcondition',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
    ]
