# Generated by Django 5.2.5 on 2026-03-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0004_alter_positionsizingrule_capital_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='allow_scaling',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='fixed_lots',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='max_position_size',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='max_position_value',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='scaling_levels',
        ),
        migrations.RemoveField(
            model_name='tradehaltcondition',
            name='strategy',
        ),
    ]
