# Generated by Django 5.2.12 on 2026-04-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0005_remove_positionsizingrule_allow_scaling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioriskprofile',
            name='max_daily_trades',
        ),
        migrations.RemoveField(
            model_name='portfolioriskprofile',
            name='max_open_positions',
        ),
        migrations.RemoveField(
            model_name='portfolioriskprofile',
            name='max_per_strategy_allocation',
        ),
        migrations.RemoveField(
            model_name='portfolioriskprofile',
            name='trailing_drawdown_reset',
        ),
        migrations.RemoveField(
            model_name='portfolioriskprofile',
            name='halt_on_breach',
        ),
        migrations.DeleteModel(
            name='TradeHaltCondition',
        ),
    ]
