# Generated by Django 5.2.12 on 2026-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_remove_portfolioriskprofile_max_daily_trades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioriskprofile',
            name='max_daily_profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily profit in rupees to halt trading', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfolioriskprofile',
            name='max_daily_profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily profit as % of capital to halt trading', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='positionsizingrule',
            name='loss_recovery_mode',
            field=models.BooleanField(default=False, help_text='Increase position size after a loss (Martingale)'),
        ),
        migrations.AddField(
            model_name='positionsizingrule',
            name='loss_recovery_multiplier',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Multiplier for position size after a loss', max_digits=5),
        ),
        migrations.AlterField(
            model_name='positionsizingrule',
            name='sizing_method',
            field=models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_FIXED', 'Risk Based (Fixed Amount)'), ('RISK_PERCENTAGE', 'Risk Based (% of Capital)'), ('VOLATILITY_ADJUSTED', 'Volatility Adjusted (ATR)')], default='CAPITAL_BASED', max_length=20),
        ),
    ]
