# Generated by Django 5.2.12 on 2026-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0007_portfolioriskprofile_max_daily_profit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyautodisable',
            name='trigger_type',
            field=models.CharField(choices=[('CONSECUTIVE_LOSSES', 'Consecutive Losses'), ('CONSECUTIVE_WINS', 'Consecutive Wins'), ('DAILY_LOSS', 'Daily Loss Threshold'), ('WEEKLY_LOSS', 'Weekly Loss Threshold'), ('MONTHLY_LOSS', 'Monthly Loss Threshold'), ('WIN_RATE_DROP', 'Win Rate Below Threshold'), ('DRAWDOWN', 'Drawdown Exceeded')], max_length=20),
        ),
    ]
