# Generated by Django 5.2.12 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0008_alter_strategyautodisable_trigger_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='loss_recovery_mode',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='loss_recovery_multiplier',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='risk_per_trade_amount',
        ),
        migrations.AlterField(
            model_name='positionsizingrule',
            name='sizing_method',
            field=models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_BASED', 'Risk Based (%)')], default='CAPITAL_BASED', max_length=20),
        ),
    ]
