# Generated by Django 5.2.12 on 2026-08-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0009_remove_positionsizingrule_loss_recovery_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='max_daily_trades',
        ),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='max_open_positions',
        ),
        migrations.RemoveField(
            model_name='strategyautodisable',
            name='require_manual_review',
        ),
    ]
