# Generated by Django 5.2.12 on 2026-10-06 17:16

from django.db import migrations, models


def remove_retired_configuration(apps, schema_editor):
    """One-time cleanup of development configurations; no runtime legacy paths."""
    sizing = apps.get_model("risk_management", "PositionSizingRule")
    sizing.objects.filter(sizing_method="RISK_BASED").update(sizing_method="CAPITAL_BASED", capital_percentage=10)
    routes = apps.get_model("instruments", "ExecutionRoute")
    routes.objects.filter(sizing_method="RISK_BASED").update(sizing_method="CAPITAL_BASED", capital_percentage=10)

    def clean(value):
        if isinstance(value, list):
            return [clean(item) for item in value]
        if not isinstance(value, dict):
            return value
        result = {key: clean(item) for key, item in value.items()
                  if key not in {"risk_per_trade_percentage", "risk_per_trade_pct", "allow_clone", "allow_backtest", "watchlist_instrument_ids"}}
        if result.get("sizing_method") == "RISK_BASED":
            result["sizing_method"] = "CAPITAL_BASED"
            result["capital_percentage"] = 10
        return result

    for app, model, fields in (
        ("strategies", "StrategyVersion", ("config_snapshot",)),
        ("backtesting", "BacktestRun", ("config_snapshot", "parameters")),
        ("research", "ResearchRun", ("request", "result", "evidence")),
        ("research", "ResearchSession", ("context",)),
        ("research", "ResearchAction", ("payload",)),
        ("audit", "AuditLog", ("old_value", "new_value")),
    ):
        model = apps.get_model(app, model)
        for row in model.objects.only("pk", *fields).iterator():
            updates = {field: clean(getattr(row, field)) for field in fields}
            updates = {field: value for field, value in updates.items() if value != getattr(row, field)}
            if updates:
                model.objects.filter(pk=row.pk).update(**updates)

    instruments = dict(apps.get_model("instruments", "Instrument").objects.values_list("pk", "symbol"))
    versions = apps.get_model("strategies", "StrategyVersion")
    for version in versions.objects.only("pk", "config_snapshot").iterator():
        snapshot = version.config_snapshot
        snapshot.setdefault("tags", [])
        for item in snapshot.get("watchlist_instruments", []):
            if item.get("instrument_id") in instruments:
                item.setdefault("instrument_symbol", instruments[item["instrument_id"]])
        versions.objects.filter(pk=version.pk).update(config_snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0012_remove_portfolio_risk_profile_and_violation'),
        ('instruments', '0010_alter_instrument_exchange'),
        ('strategies', '0023_alter_strategy_visibility'),
        ('backtesting', '0018_backtestrun_diagnostics'),
        ('research', '0004_conversation_contract'),
        ('audit', '0003_current_execution_flow'),
    ]

    operations = [
        migrations.RunPython(remove_retired_configuration, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='positionsizingrule',
            name='risk_per_trade_percentage',
        ),
        migrations.AlterField(
            model_name='positionsizingrule',
            name='sizing_method',
            field=models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based')], default='CAPITAL_BASED', max_length=20),
        ),
    ]
