# Generated by Django 5.2.5 on 2026-01-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('NFO', 'NSE Futures & Options'), ('BFO', 'BSE Futures & Options'), ('MCX', 'Multi Commodity Exchange'), ('CDS', 'Currency Derivatives'), ('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], max_length=20)),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('FUTURE', 'Future'), ('OPTION', 'Option Contract'), ('CURRENCY', 'Currency Pair'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('avg_volume', models.BigIntegerField(blank=True, null=True)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=10)),
                ('circuit_limit_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('circuit_limit_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_tradeable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='instruments_symbol_9f0e0f_idx'), models.Index(fields=['exchange', 'instrument_type'], name='instruments_exchang_bfbc39_idx'), models.Index(fields=['sector'], name='instruments_sector_d76c2c_idx')],
                'unique_together': {('symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_type', models.CharField(choices=[('SECTOR', 'Sector'), ('MARKET_CAP', 'Market Cap'), ('VOLUME', 'Volume/Liquidity'), ('VOLATILITY', 'Volatility'), ('PRICE', 'Price Range')], max_length=20)),
                ('operator', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CROSSES_ABOVE', 'Crosses Above'), ('CROSSES_BELOW', 'Crosses Below'), ('BETWEEN', 'Between')], max_length=20)),
                ('value', models.JSONField(help_text='Filter value(s) in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_filters', to='strategies.strategy')),
            ],
            options={
                'ordering': ['filter_type'],
            },
        ),
        migrations.CreateModel(
            name='OptionSelectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('strike_logic', models.CharField(choices=[('ATM', 'At The Money'), ('ITM_1', 'ITM 1 Strike'), ('ITM_2', 'ITM 2 Strikes'), ('ITM_3', 'ITM 3 Strikes'), ('OTM_1', 'OTM 1 Strike'), ('OTM_2', 'OTM 2 Strikes'), ('OTM_3', 'OTM 3 Strikes'), ('CLOSEST_PREMIUM', 'Closest to Premium'), ('DELTA_BASED', 'Delta Based')], default='ATM', max_length=20)),
                ('delta_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('delta_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('expiry_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEAREST', 'Nearest Expiry')], default='NEAREST', max_length=20)),
                ('min_oi', models.BigIntegerField(blank=True, help_text='Minimum open interest', null=True)),
                ('iv_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('iv_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('theta_min', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('premium_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_selection_rules', to='strategies.strategy')),
                ('underlying', models.ForeignKey(blank=True, help_text='Specific underlying or null for dynamic selection', null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
            options={
                'ordering': ['strategy', 'option_type'],
            },
        ),
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry', models.DateField()),
                ('option_type', models.CharField(choices=[('CE', 'Call Option'), ('PE', 'Put Option')], max_length=5)),
                ('lot_size', models.IntegerField(default=1)),
                ('iv', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('vega', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_contracts', to='instruments.instrument')),
            ],
            options={
                'indexes': [models.Index(fields=['underlying', 'expiry'], name='instruments_underly_b781e6_idx'), models.Index(fields=['symbol'], name='instruments_symbol_f26395_idx')],
                'unique_together': {('underlying', 'strike', 'expiry', 'option_type')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_instruments', to='strategies.strategy')),
            ],
            options={
                'unique_together': {('strategy', 'instrument')},
            },
        ),
    ]
