# Generated by Django 5.2.5 on 2026-02-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instrument',
            name='instruments_sector_d76c2c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instrument',
            name='asm_gsm_flag',
            field=models.CharField(blank=True, default='', help_text='ASM/GSM surveillance indicator', max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='currency_code',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='instrument',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Mobile-friendly display name', max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_inst_type',
            field=models.IntegerField(choices=[(0, 'EQ (Equity)'), (1, 'Preference Shares'), (2, 'Debentures'), (3, 'Warrants'), (4, 'Misc (NSE/BSE)'), (5, 'Sovereign Gold Bond'), (6, 'Government Securities'), (7, 'Treasury Bills'), (8, 'Mutual Fund'), (9, 'Exchange Traded Fund'), (10, 'Index'), (11, 'Index Futures'), (12, 'VIX Futures'), (13, 'Stock Futures'), (14, 'Index Options'), (15, 'Stock Options'), (16, 'Currency Futures'), (17, 'Interest Rate Futures (T)'), (18, 'Interest Rate Futures (C)'), (19, 'Currency Options'), (20, 'Underlying Currency'), (21, 'Underlying IRC'), (22, 'Underlying IRT'), (23, 'Underlying IRD'), (24, 'Currency Index'), (25, 'Interest Rate Futures (D)'), (30, 'Commodity Futures'), (31, 'Options on Futures'), (32, 'Commodity Options'), (33, 'Basis Futures'), (34, 'Bullion Futures'), (35, 'Energy Futures'), (36, 'Bullion Options'), (37, 'Options on Futures (NCOM)'), (50, 'Misc (BSE)')], default=0, help_text='Exchange instrument type code'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='exchange_token',
            field=models.IntegerField(default=0, help_text='Exchange-assigned token (exToken)'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='fy_token',
            field=models.CharField(db_index=True, default='', help_text='Fyers unique token (e.g. 101000000016921)', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='has_futures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_mtf_tradable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='isin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_sync_date',
            field=models.DateField(blank=True, help_text='Fyers lastUpdate date', null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='mtf_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MTF margin multiplier (e.g. 2.9x)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='option_type',
            field=models.CharField(blank=True, default='XX', help_text='CE/PE/XX', max_length=5),
        ),
        migrations.AddField(
            model_name='instrument',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='previous_oi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='qty_freeze',
            field=models.IntegerField(blank=True, help_text='Freeze quantity limit', null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='qty_multiplier',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='instrument',
            name='segment',
            field=models.IntegerField(choices=[(10, 'Capital Market'), (11, 'Equity Derivatives'), (12, 'Currency Derivatives'), (20, 'Commodity Derivatives')], default=10, help_text='10=CM, 11=FO, 12=CD, 20=COM'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='series',
            field=models.CharField(blank=True, default='', help_text='e.g. EQ, BE, FUT', max_length=10),
        ),
        migrations.AddField(
            model_name='instrument',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='instrument',
            name='stream',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instrument',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='-1 for non-options', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='sym_ticker',
            field=models.CharField(default='', help_text='Full Fyers symbol (e.g. NSE:SBIN-EQ)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='trading_session',
            field=models.CharField(blank=True, default='', help_text='e.g. 0915-1530|1815-1915:', max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='underlying_fy_token',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='instrument',
            name='underlying_symbol',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='circuit_limit_lower',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='circuit_limit_upper',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('FUTURE', 'Future'), ('OPTION', 'Option Contract'), ('CURRENCY', 'Currency Pair'), ('COMMODITY', 'Commodity')], help_text='Derived from ex_inst_type during sync', max_length=20),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['sym_ticker'], name='instruments_sym_tic_eef8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['exchange', 'segment'], name='instruments_exchang_6d3c93_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['underlying_symbol'], name='instruments_underly_0322cc_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['isin'], name='instruments_isin_2f2a35_idx'),
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='avg_volume',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='sector',
        ),
    ]
