# Generated by Django 5.2.5 on 2026-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_remove_instrument_instruments_sector_d76c2c_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optioncontract',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='underlying',
        ),
        migrations.RemoveField(
            model_name='optionselectionrule',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='optionselectionrule',
            name='underlying',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('MCX', 'Multi Commodity Exchange'), ('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('FUTURE', 'Future'), ('OPTION', 'Option Contract'), ('CURRENCY', 'Currency Pair'), ('COMMODITY', 'Commodity'), ('ETF', 'Exchange Traded Fund'), ('BOND', 'Bond / Govt Securities'), ('MF', 'Mutual Fund')], help_text='Derived from ex_inst_type during sync', max_length=20),
        ),
        migrations.DeleteModel(
            name='InstrumentFilter',
        ),
        migrations.DeleteModel(
            name='OptionContract',
        ),
        migrations.DeleteModel(
            name='OptionSelectionRule',
        ),
    ]
