# Generated by Django 5.2.12 on 2026-06-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_type', models.CharField(choices=[('DIRECT', 'Trade Same Instrument'), ('MANUAL', 'Specific Instrument'), ('FUTURES', 'Dynamic Futures'), ('OPTIONS', 'Dynamic Options')], default='DIRECT', max_length=20)),
                ('expiry_preference', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEAREST', 'Nearest Expiry')], default='NEAREST', max_length=20)),
                ('buy_signal_option_type', models.CharField(choices=[('CE', 'Call Option'), ('PE', 'Put Option')], default='CE', max_length=5)),
                ('sell_signal_option_type', models.CharField(choices=[('CE', 'Call Option'), ('PE', 'Put Option')], default='PE', max_length=5)),
                ('strike_selection', models.CharField(choices=[('ATM', 'At The Money'), ('ITM_1', 'ITM 1 Strike'), ('ITM_2', 'ITM 2 Strikes'), ('ITM_3', 'ITM 3 Strikes'), ('OTM_1', 'OTM 1 Strike'), ('OTM_2', 'OTM 2 Strikes'), ('OTM_3', 'OTM 3 Strikes'), ('CLOSEST_PREMIUM', 'Closest to Premium'), ('DELTA_BASED', 'Delta Based')], default='ATM', max_length=20)),
                ('override_sizing', models.BooleanField(default=False, help_text='When enabled, this instrument uses its own sizing config instead of the strategy default.')),
                ('sizing_method', models.CharField(blank=True, choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_FIXED', 'Risk Based (Fixed Amount)'), ('RISK_PERCENTAGE', 'Risk Based (% of Capital)')], help_text='Overrides strategy sizing method (FIXED, CAPITAL_BASED, RISK_FIXED, RISK_PERCENTAGE)', max_length=20, null=True)),
                ('fixed_quantity', models.IntegerField(blank=True, help_text='For FIXED method: exact quantity (will be rounded to lot size)', null=True)),
                ('capital_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='For CAPITAL_BASED method: percent of portfolio capital to allocate', max_digits=6, null=True)),
                ('risk_per_trade_amount', models.DecimalField(blank=True, decimal_places=2, help_text='For RISK_FIXED method: fixed rupee amount to risk per trade', max_digits=12, null=True)),
                ('risk_per_trade_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='For RISK_PERCENTAGE method: percent of portfolio capital to risk per trade', max_digits=6, null=True)),
                ('target_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_from', to='instruments.instrument')),
                ('target_underlying_instrument', models.ForeignKey(blank=True, help_text='The underlying instrument whose derivatives to trade. Enables cross-symbol routing (e.g., signal on NIFTY → trade BANKNIFTY options).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underlying_routes', to='instruments.instrument')),
                ('watchlist_instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_route', to='instruments.watchlistinstrument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
