# Generated by Django 5.2.12 on 2026-06-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_executionroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionroute',
            name='watchlist_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_routes', to='instruments.watchlistinstrument'),
        ),
    ]
