# Generated by Django 5.2.12 on 2026-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_executionroute_watchlist_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionroute',
            name='avoid_same_day_expiry',
            field=models.BooleanField(default=False, help_text='If True, on the day of expiry, it will automatically roll over to the next expiry to avoid Gamma risk.'),
        ),
        migrations.AlterField(
            model_name='executionroute',
            name='strike_selection',
            field=models.CharField(choices=[('ATM', 'At The Money'), ('ITM_1', 'ITM 1 Strike'), ('ITM_2', 'ITM 2 Strikes'), ('ITM_3', 'ITM 3 Strikes'), ('OTM_1', 'OTM 1 Strike'), ('OTM_2', 'OTM 2 Strikes'), ('OTM_3', 'OTM 3 Strikes')], default='ATM', max_length=20),
        ),
    ]
