# Generated by Django 5.2.12 on 2026-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_executionroute_avoid_same_day_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionroute',
            name='sizing_method',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_FIXED', 'Risk Based (Fixed Amount)'), ('RISK_PERCENTAGE', 'Risk Based (% of Capital)'), ('VOLATILITY_ADJUSTED', 'Volatility Adjusted (ATR)')], help_text='Overrides strategy sizing method (FIXED, CAPITAL_BASED, RISK_FIXED, RISK_PERCENTAGE)', max_length=20, null=True),
        ),
    ]
