# Generated by Django 5.2.12 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_alter_executionroute_sizing_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionroute',
            name='sizing_method',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_BASED', 'Risk Based (%)')], help_text='Overrides strategy sizing method (FIXED, CAPITAL_BASED, RISK_FIXED, RISK_PERCENTAGE)', max_length=20, null=True),
        ),
    ]
