# Generated by Django 5.2.12 on 2026-08-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_alter_executionroute_sizing_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionroute',
            name='risk_per_trade_amount',
        ),
    ]
