# Generated by Django 5.2.12 on 2026-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0009_remove_executionroute_risk_per_trade_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('MCX', 'Multi Commodity Exchange')], max_length=20),
        ),
    ]
