# Generated by Django 5.2.12 on 2026-10-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_alter_instrument_exchange'),
        ('risk_management', '0013_remove_positionsizingrule_risk_per_trade_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionroute',
            name='risk_per_trade_percentage',
        ),
        migrations.AlterField(
            model_name='executionroute',
            name='sizing_method',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based')], help_text='Overrides strategy sizing method (FIXED or CAPITAL_BASED)', max_length=20, null=True),
        ),
    ]
