# Generated by Django 5.2.5 on 2026-01-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rule_type', models.CharField(choices=[('ENTRY', 'Entry Rule'), ('EXIT', 'Exit Rule'), ('STOP_LOSS', 'Stop Loss Rule'), ('TARGET', 'Target Rule')], default='ENTRY', max_length=20)),
                ('logical_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=10)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Evaluation priority (lower = higher priority)')),
                ('is_sequential', models.BooleanField(default=False, help_text='Rules must be satisfied in sequence')),
                ('min_confirmations', models.PositiveIntegerField(default=1, help_text='Minimum number of rules that must be true')),
                ('lookback_window', models.PositiveIntegerField(default=1, help_text='Number of candles to look back for sequential rules')),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='strategies.strategy')),
            ],
            options={
                'ordering': ['rule_type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('INDICATOR', 'Indicator-based'), ('PRICE_ACTION', 'Price Action'), ('VOLUME', 'Volume-based'), ('CUSTOM', 'Custom')], default='INDICATOR', max_length=20)),
                ('indicator_type', models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], max_length=30, null=True)),
                ('price_action_type', models.CharField(blank=True, choices=[('BREAKOUT_HIGH', 'Breakout Above High'), ('BREAKDOWN_LOW', 'Breakdown Below Low'), ('SUPPORT_BREAKOUT', 'Support Breakout'), ('RESISTANCE_BREAKOUT', 'Resistance Breakout'), ('INSIDE_CANDLE', 'Inside Candle'), ('OUTSIDE_CANDLE', 'Outside Candle'), ('ENGULFING_BULLISH', 'Bullish Engulfing'), ('ENGULFING_BEARISH', 'Bearish Engulfing'), ('DOJI', 'Doji'), ('HAMMER', 'Hammer'), ('SHOOTING_STAR', 'Shooting Star'), ('MORNING_STAR', 'Morning Star'), ('EVENING_STAR', 'Evening Star'), ('HIGHER_HIGH', 'Higher High'), ('HIGHER_LOW', 'Higher Low'), ('LOWER_HIGH', 'Lower High'), ('LOWER_LOW', 'Lower Low'), ('GAP_UP', 'Gap Up'), ('GAP_DOWN', 'Gap Down'), ('RANGE_BREAKOUT', 'Range Breakout'), ('PREV_DAY_HIGH', 'Previous Day High'), ('PREV_DAY_LOW', 'Previous Day Low')], max_length=30, null=True)),
                ('volume_condition_type', models.CharField(blank=True, choices=[('VOLUME_SPIKE', 'Volume Spike'), ('VOLUME_ABOVE_AVG', 'Volume Above Average'), ('VOLUME_DIVERGENCE', 'Volume Divergence')], max_length=30, null=True)),
                ('params', models.JSONField(blank=True, help_text="Indicator parameters: {period: 14, source: 'close', ...}", null=True)),
                ('comparison', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CROSSES_ABOVE', 'Crosses Above'), ('CROSSES_BELOW', 'Crosses Below'), ('BETWEEN', 'Between')], default='GT', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=4, help_text='Comparison value', max_digits=15, null=True)),
                ('value2', models.DecimalField(blank=True, decimal_places=4, help_text='Second value for BETWEEN comparisons', max_digits=15, null=True)),
                ('compare_to_indicator', models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], help_text='Compare to another indicator (for crossovers)', max_length=30, null=True)),
                ('compare_to_params', models.JSONField(blank=True, help_text='Parameters for comparison indicator', null=True)),
                ('timeframe_override', models.CharField(blank=True, choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week')], help_text='Use different timeframe for this rule', max_length=10, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=1, help_text='Order in sequential rule evaluation')),
                ('is_active', models.BooleanField(default=True)),
                ('rule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules_engine.rulegroup')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialEventFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avoid_earnings', models.BooleanField(default=False, help_text='Avoid trading on earnings announcement days')),
                ('avoid_news', models.BooleanField(default=False, help_text='Avoid trading during major news events')),
                ('avoid_expiry_day', models.BooleanField(default=True, help_text='Avoid trading on F&O expiry days')),
                ('avoid_rbi_policy', models.BooleanField(default=False, help_text='Avoid trading on RBI policy days')),
                ('custom_avoid_dates', models.JSONField(blank=True, help_text="Custom dates to avoid trading: ['2024-01-26', ...]", null=True)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_event_filter', to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StopLossRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sl_type', models.CharField(choices=[('FIXED_POINTS', 'Fixed Points'), ('FIXED_PERCENTAGE', 'Fixed Percentage'), ('ATR_BASED', 'ATR Based'), ('CANDLE_BASED', 'Candle Based'), ('TRAILING_FIXED', 'Trailing Fixed'), ('TRAILING_PERCENTAGE', 'Trailing Percentage'), ('TRAILING_INDICATOR', 'Trailing Indicator-based'), ('TIME_BASED', 'Time Based'), ('EMERGENCY', 'Emergency')], default='FIXED_PERCENTAGE', max_length=30)),
                ('fixed_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('atr_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('atr_period', models.PositiveIntegerField(default=14)),
                ('candle_reference', models.CharField(blank=True, choices=[('LOW', 'Candle Low'), ('HIGH', 'Candle High'), ('PREV_CANDLE', 'Previous Candle')], max_length=20, null=True)),
                ('candle_lookback', models.PositiveIntegerField(default=1, help_text='Number of candles to look back')),
                ('trailing_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed Points'), ('PERCENTAGE', 'Percentage'), ('INDICATOR', 'Indicator-based')], max_length=20, null=True)),
                ('trailing_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trailing_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trailing_indicator', models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], max_length=30, null=True)),
                ('trailing_params', models.JSONField(blank=True, null=True)),
                ('time_minutes', models.PositiveIntegerField(blank=True, help_text='Exit after X minutes in loss', null=True)),
                ('emergency_loss_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Emergency exit if loss exceeds this %', max_digits=5, null=True)),
                ('is_broker_side', models.BooleanField(default=False, help_text='Place stop order with broker')),
                ('move_to_cost_after_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Move SL to entry price after X% profit', max_digits=5, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_loss_rules', to='strategies.strategy')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TargetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('target_type', models.CharField(choices=[('FIXED_POINTS', 'Fixed Points'), ('FIXED_PERCENTAGE', 'Fixed Percentage'), ('RISK_REWARD', 'Risk-Reward Ratio'), ('INDICATOR_BASED', 'Indicator Based'), ('TRAILING', 'Trailing'), ('TIME_BASED', 'Time Based'), ('EOD', 'End of Day'), ('EXPIRY', 'Expiry Exit')], default='FIXED_PERCENTAGE', max_length=30)),
                ('fixed_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Target = SL * ratio (e.g., 2.0 for 1:2)', max_digits=4, null=True)),
                ('indicator_type', models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], max_length=30, null=True)),
                ('indicator_params', models.JSONField(blank=True, null=True)),
                ('trailing_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed Points'), ('PERCENTAGE', 'Percentage')], max_length=20, null=True)),
                ('trailing_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partial_booking_levels', models.JSONField(blank=True, help_text='[{exit_pct: 50, at_profit_pct: 1.5}, ...]', null=True)),
                ('time_exit_minutes', models.PositiveIntegerField(blank=True, help_text='Exit after X minutes regardless of P&L', null=True)),
                ('eod_squareoff_time', models.TimeField(blank=True, help_text='Square off time for intraday', null=True)),
                ('expiry_exit_minutes_before', models.PositiveIntegerField(blank=True, help_text='Exit X minutes before expiry', null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='strategies.strategy')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_days', models.JSONField(default=list, help_text="List of trading days: ['Monday', 'Tuesday', ...]")),
                ('market_session', models.CharField(choices=[('PRE_MARKET', 'Pre-Market'), ('MARKET_OPEN', 'Market Open'), ('MARKET_CLOSE', 'Market Close'), ('ALL', 'All Sessions')], default='ALL', max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Start time for trading (IST)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for trading (IST)', null=True)),
                ('candle_timeframe', models.CharField(choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week')], default='5m', max_length=10)),
                ('candle_completion_rule', models.CharField(choices=[('ON_CLOSE', 'On Candle Close'), ('ON_OPEN', 'On Candle Open'), ('REAL_TIME', 'Real-time Tick')], default='ON_CLOSE', max_length=20)),
                ('no_trade_windows', models.JSONField(blank=True, help_text="Time windows to avoid: [{start: '13:00', end: '14:00'}, ...]", null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_rule', to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
