# Generated by Django 5.2.5 on 2026-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoplossrule',
            name='candle_reference',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='trailing_type',
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='candle_offset',
            field=models.PositiveIntegerField(default=0, help_text='0=Current Candle, 1=Previous Candle'),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='candle_part',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('HIGH', 'High'), ('LOW', 'Low'), ('CLOSE', 'Close')], help_text='Part of candle to use (Low, High, etc.)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='indicator_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='indicator_type',
            field=models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='operator',
            field=models.CharField(blank=True, choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CROSSES_ABOVE', 'Crosses Above'), ('CROSSES_BELOW', 'Crosses Below'), ('BETWEEN', 'Between')], default='GT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Value to compare indicator against', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='operator',
            field=models.CharField(blank=True, choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CROSSES_ABOVE', 'Crosses Above'), ('CROSSES_BELOW', 'Crosses Below'), ('BETWEEN', 'Between')], default='GT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Value to compare indicator against', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stoplossrule',
            name='sl_type',
            field=models.CharField(choices=[('FIXED_POINTS', 'Fixed Points'), ('FIXED_PERCENTAGE', 'Fixed Percentage'), ('ATR_BASED', 'ATR Based'), ('CANDLE_BASED', 'Candle Based'), ('TRAILING_FIXED', 'Trailing Fixed'), ('TRAILING_PERCENTAGE', 'Trailing Percentage'), ('TRAILING_INDICATOR', 'Trailing Indicator-based'), ('INDICATOR_BASED', 'Indicator Condition'), ('TIME_BASED', 'Time Based'), ('EMERGENCY', 'Emergency')], default='FIXED_PERCENTAGE', max_length=30),
        ),
    ]
