# Generated by Django 5.2.5 on 2026-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0002_remove_stoplossrule_candle_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoplossrule',
            name='compare_to_indicator',
            field=models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], help_text='Compare to another indicator (for crossovers)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='compare_to_params',
            field=models.JSONField(blank=True, help_text='Parameters for comparison indicator', null=True),
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='timeframe_override',
            field=models.CharField(blank=True, choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week')], help_text='Use different timeframe for this rule', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='compare_to_indicator',
            field=models.CharField(blank=True, choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD Line'), ('MACD_SIGNAL', 'MACD Signal Line'), ('MACD_HISTOGRAM', 'MACD Histogram'), ('BOLLINGER_UPPER', 'Bollinger Upper Band'), ('BOLLINGER_LOWER', 'Bollinger Lower Band'), ('BOLLINGER_MID', 'Bollinger Middle Band'), ('VWAP', 'Volume Weighted Average Price'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('PLUS_DI', '+DI'), ('MINUS_DI', '-DI'), ('STOCHASTIC_K', 'Stochastic %K'), ('STOCHASTIC_D', 'Stochastic %D'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point')], help_text='Compare to another indicator (for crossovers)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='compare_to_params',
            field=models.JSONField(blank=True, help_text='Parameters for comparison indicator', null=True),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='timeframe_override',
            field=models.CharField(blank=True, choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week')], help_text='Use different timeframe for this rule', max_length=10, null=True),
        ),
    ]
