# Generated by Django 5.2.5 on 2026-02-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0003_stoplossrule_compare_to_indicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoplossrule',
            name='atr_multiplier',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='atr_period',
        ),
    ]
