# Generated by Django 5.2.5 on 2026-02-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0004_remove_stoplossrule_atr_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoplossrule',
            name='trailing_indicator',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='trailing_params',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='trailing_percentage',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='trailing_points',
        ),
        migrations.RemoveField(
            model_name='targetrule',
            name='trailing_type',
        ),
        migrations.AddField(
            model_name='stoplossrule',
            name='trailing_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trailing value (points or percentage based on type)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stoplossrule',
            name='sl_type',
            field=models.CharField(choices=[('FIXED_POINTS', 'Fixed Points'), ('FIXED_PERCENTAGE', 'Fixed Percentage'), ('CANDLE_BASED', 'Candle Based'), ('TRAILING_FIXED', 'Trailing Fixed'), ('TRAILING_PERCENTAGE', 'Trailing Percentage'), ('TRAILING_INDICATOR', 'Trailing Indicator-based'), ('INDICATOR_BASED', 'Indicator Condition'), ('TIME_BASED', 'Time Based'), ('EMERGENCY', 'Emergency')], default='FIXED_PERCENTAGE', max_length=30),
        ),
        migrations.AlterField(
            model_name='targetrule',
            name='target_type',
            field=models.CharField(choices=[('FIXED_POINTS', 'Fixed Points'), ('FIXED_PERCENTAGE', 'Fixed Percentage'), ('RISK_REWARD', 'Risk-Reward Ratio'), ('INDICATOR_BASED', 'Indicator Based'), ('TRAILING_FIXED', 'Trailing Fixed'), ('TRAILING_PERCENTAGE', 'Trailing Percentage'), ('TIME_BASED', 'Time Based'), ('EOD', 'End of Day'), ('EXPIRY', 'Expiry Exit')], default='FIXED_PERCENTAGE', max_length=30),
        ),
    ]
