# Generated by Django 5.2.5 on 2026-02-15 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0005_remove_stoplossrule_trailing_indicator_and_more'),
        ('strategies', '0005_entryorderconfig_entry_group_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoplossrule',
            name='rule_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_loss_rules', to='rules_engine.rulegroup'),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='rule_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='rules_engine.rulegroup'),
        ),
        migrations.AlterField(
            model_name='stoplossrule',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_loss_rules', to='strategies.strategy'),
        ),
        migrations.AlterField(
            model_name='targetrule',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='strategies.strategy'),
        ),
    ]
