# Generated by Django 5.2.5 on 2026-02-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0006_stoplossrule_rule_group_targetrule_rule_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoplossrule',
            name='is_broker_side',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='move_to_cost_after_pct',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='targetrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='targetrule',
            name='partial_booking_levels',
        ),
        migrations.RemoveField(
            model_name='targetrule',
            name='strategy',
        ),
    ]
