# Generated by Django 5.2.5 on 2026-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0007_remove_stoplossrule_is_broker_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoplossrule',
            name='threshold_value2',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Second value for BETWEEN comparisons', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='threshold_value2',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Second value for BETWEEN comparisons', max_digits=15, null=True),
        ),
    ]
