# Generated by Django 5.2.5 on 2026-02-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0008_stoplossrule_threshold_value2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='sequence_order',
        ),
        migrations.RemoveField(
            model_name='rulegroup',
            name='is_sequential',
        ),
        migrations.RemoveField(
            model_name='rulegroup',
            name='lookback_window',
        ),
        migrations.RemoveField(
            model_name='rulegroup',
            name='min_confirmations',
        ),
    ]
