# Generated by Django 5.2.5 on 2026-02-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0009_alter_rule_options_remove_rule_sequence_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoplossrule',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='targetrule',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='stoplossrule',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='targetrule',
            name='priority',
        ),
    ]
