# Generated by Django 5.2.5 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0010_alter_stoplossrule_options_alter_targetrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerule',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata (IST)'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York (EST/EDT)'), ('Europe/London', 'Europe/London (GMT/BST)'), ('Asia/Tokyo', 'Asia/Tokyo (JST)'), ('Australia/Sydney', 'Australia/Sydney (AEST/AEDT)')], default='Asia/Kolkata', max_length=50),
        ),
    ]
