# Generated by Django 5.2.12 on 2026-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0011_alter_timerule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegroup',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy / Long'), ('SELL', 'Sell / Short')], default='BUY', help_text='Trade direction for ENTRY groups (BUY=Long, SELL=Short)', max_length=10),
        ),
    ]
