# Generated by Django 5.2.12 on 2026-04-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0012_add_side_to_rulegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulegroup',
            name='side',
        ),
    ]
