# Generated by Django 5.2.12 on 2026-05-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0013_remove_side_from_rulegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulegroup',
            name='rule_type',
            field=models.CharField(choices=[('ENTRY', 'Entry Rule'), ('STOP_LOSS', 'Stop Loss Rule'), ('TARGET', 'Target Rule')], default='ENTRY', max_length=20),
        ),
    ]
