# Generated by Django 5.2.12 on 2026-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0014_alter_rulegroup_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulegroup',
            name='rule_type',
            field=models.CharField(choices=[('ENTRY', 'Entry Rule'), ('EXIT', 'Exit Rule'), ('STOP_LOSS', 'Stop Loss Rule'), ('TARGET', 'Target Rule')], default='ENTRY', max_length=20),
        ),
    ]
