# Generated by Django 5.2.12 on 2026-07-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0015_alter_rulegroup_rule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialeventfilter',
            name='avoid_expiry_day',
        ),
    ]
