# Generated by Django 5.2.12 on 2026-07-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0016_remove_specialeventfilter_avoid_expiry_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetrule',
            name='rule_group',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='compare_to_indicator',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='compare_to_params',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='indicator_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='params',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='price_action_type',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='timeframe_override',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='value',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='volume_condition_type',
        ),
        migrations.AddField(
            model_name='rule',
            name='operand_a_params',
            field=models.JSONField(blank=True, help_text='Parameters for Operand A', null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='operand_a_timeframe',
            field=models.CharField(blank=True, choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week')], help_text='Timeframe override for Operand A', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='operand_a_type',
            field=models.CharField(choices=[('LTP', 'Last Traded Price'), ('OPEN', 'Open Price'), ('HIGH', 'High Price'), ('LOW', 'Low Price'), ('CLOSE', 'Close Price'), ('VOLUME', 'Volume'), ('VWAP', 'Volume Weighted Average Price'), ('HL2', 'HL2'), ('HLC3', 'HLC3'), ('OHLC4', 'OHLC4'), ('CURRENT_DAY_OPEN', 'Current Day Open'), ('PREV_WEEK_HIGH', 'Previous Week High'), ('PREV_WEEK_LOW', 'Previous Week Low'), ('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('HMA', 'Hull Moving Average'), ('ALMA', 'Arnaud Legoux Moving Average'), ('KAMA', 'Kaufman Adaptive Moving Average'), ('DEMA', 'Double Exponential Moving Average'), ('TEMA', 'Triple Exponential Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD'), ('BOLLINGER_BANDS', 'Bollinger Bands'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('DMI', 'Directional Movement Index'), ('STOCHASTIC', 'Stochastic'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point'), ('KELTNER_CHANNEL', 'Keltner Channel'), ('DONCHIAN_CHANNEL', 'Donchian Channel'), ('ZIGZAG', 'ZigZag'), ('PARABOLIC_SAR', 'Parabolic SAR'), ('ICHIMOKU_CLOUD', 'Ichimoku Cloud'), ('IMPLIED_VOLATILITY', 'Implied Volatility'), ('DELTA', 'Delta'), ('THETA', 'Theta'), ('OPEN_INTEREST', 'Open Interest'), ('PCR', 'Put-Call Ratio'), ('MAX_PAIN', 'Max Pain'), ('POSITION_PNL_PERCENTAGE', 'Position PnL %'), ('POSITION_PNL_POINTS', 'Position PnL Points'), ('TRAILING_PEAK_OFFSET', 'Trailing Peak Offset'), ('ENTRY_PRICE', 'Entry Price'), ('MOVE_TO_BREAKEVEN', 'Move to Breakeven'), ('TIME_DECAY', 'Time Decay Exit'), ('CONSTANT', 'Constant Value'), ('MATH_EXPRESSION', 'Math Expression')], default='LTP', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='operand_b_params',
            field=models.JSONField(blank=True, help_text="Parameters for Operand B (e.g., {'value': 100})", null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='operand_b_timeframe',
            field=models.CharField(blank=True, choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week')], help_text='Timeframe override for Operand B', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='operand_b_type',
            field=models.CharField(choices=[('LTP', 'Last Traded Price'), ('OPEN', 'Open Price'), ('HIGH', 'High Price'), ('LOW', 'Low Price'), ('CLOSE', 'Close Price'), ('VOLUME', 'Volume'), ('VWAP', 'Volume Weighted Average Price'), ('HL2', 'HL2'), ('HLC3', 'HLC3'), ('OHLC4', 'OHLC4'), ('CURRENT_DAY_OPEN', 'Current Day Open'), ('PREV_WEEK_HIGH', 'Previous Week High'), ('PREV_WEEK_LOW', 'Previous Week Low'), ('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('HMA', 'Hull Moving Average'), ('ALMA', 'Arnaud Legoux Moving Average'), ('KAMA', 'Kaufman Adaptive Moving Average'), ('DEMA', 'Double Exponential Moving Average'), ('TEMA', 'Triple Exponential Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'MACD'), ('BOLLINGER_BANDS', 'Bollinger Bands'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('DMI', 'Directional Movement Index'), ('STOCHASTIC', 'Stochastic'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point'), ('KELTNER_CHANNEL', 'Keltner Channel'), ('DONCHIAN_CHANNEL', 'Donchian Channel'), ('ZIGZAG', 'ZigZag'), ('PARABOLIC_SAR', 'Parabolic SAR'), ('ICHIMOKU_CLOUD', 'Ichimoku Cloud'), ('IMPLIED_VOLATILITY', 'Implied Volatility'), ('DELTA', 'Delta'), ('THETA', 'Theta'), ('OPEN_INTEREST', 'Open Interest'), ('PCR', 'Put-Call Ratio'), ('MAX_PAIN', 'Max Pain'), ('POSITION_PNL_PERCENTAGE', 'Position PnL %'), ('POSITION_PNL_POINTS', 'Position PnL Points'), ('TRAILING_PEAK_OFFSET', 'Trailing Peak Offset'), ('ENTRY_PRICE', 'Entry Price'), ('MOVE_TO_BREAKEVEN', 'Move to Breakeven'), ('TIME_DECAY', 'Time Decay Exit'), ('CONSTANT', 'Constant Value'), ('MATH_EXPRESSION', 'Math Expression')], default='CONSTANT', max_length=50),
        ),
        migrations.DeleteModel(
            name='StopLossRule',
        ),
        migrations.DeleteModel(
            name='TargetRule',
        ),
    ]
