# Generated by Django 5.2.12 on 2026-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0017_remove_targetrule_rule_group_remove_rule_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegroup',
            name='action',
            field=models.CharField(choices=[('EXIT_ALL', 'Exit Full Position'), ('PARTIAL_EXIT', 'Partial Exit'), ('MOVE_TO_BREAKEVEN', 'Move Stop Loss to Breakeven')], default='EXIT_ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='rulegroup',
            name='action_params',
            field=models.JSONField(blank=True, help_text="Params for action, e.g., {'exit_pct': 50}", null=True),
        ),
    ]
