# Generated by Django 5.2.12 on 2026-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0018_rulegroup_action_rulegroup_action_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='comparison',
            field=models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CROSSES_ABOVE', 'Crosses Above'), ('CROSSES_BELOW', 'Crosses Below')], default='GT', max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operand_a_type',
            field=models.CharField(choices=[('LTP', 'Last Traded Price'), ('OPEN', 'Open Price'), ('HIGH', 'High Price'), ('LOW', 'Low Price'), ('CLOSE', 'Close Price'), ('VOLUME', 'Volume'), ('VWAP', 'Volume Weighted Average Price'), ('HL2', 'HL2'), ('HLC3', 'HLC3'), ('OHLC4', 'OHLC4'), ('CURRENT_DAY_OPEN', 'Current Day Open'), ('PREV_WEEK_HIGH', 'Previous Week High'), ('PREV_WEEK_LOW', 'Previous Week Low'), ('CANDLE_PATTERN', 'Candle Pattern'), ('CANDLE_BODY_SIZE', 'Candle Body Size'), ('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('HMA', 'Hull Moving Average'), ('ALMA', 'Arnaud Legoux Moving Average'), ('KAMA', 'Kaufman Adaptive Moving Average'), ('DEMA', 'Double Exponential Moving Average'), ('TEMA', 'Triple Exponential Moving Average'), ('RSI', 'Relative Strength Index'), ('ROC', 'Rate of Change'), ('MACD', 'MACD'), ('BOLLINGER_BANDS', 'Bollinger Bands'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('DMI', 'Directional Movement Index'), ('STOCHASTIC', 'Stochastic'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point'), ('KELTNER_CHANNEL', 'Keltner Channel'), ('DONCHIAN_CHANNEL', 'Donchian Channel'), ('PARABOLIC_SAR', 'Parabolic SAR'), ('ICHIMOKU_CLOUD', 'Ichimoku Cloud'), ('POSITION_PNL_PERCENTAGE', 'Position PnL %'), ('POSITION_PNL_POINTS', 'Position PnL Points'), ('TRAILING_PEAK_OFFSET', 'Trailing Peak Offset'), ('ENTRY_PRICE', 'Entry Price'), ('TIME_DECAY', 'Time Decay Exit'), ('CONSTANT', 'Constant Value'), ('MATH_EXPRESSION', 'Math Expression')], default='LTP', max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operand_b_type',
            field=models.CharField(choices=[('LTP', 'Last Traded Price'), ('OPEN', 'Open Price'), ('HIGH', 'High Price'), ('LOW', 'Low Price'), ('CLOSE', 'Close Price'), ('VOLUME', 'Volume'), ('VWAP', 'Volume Weighted Average Price'), ('HL2', 'HL2'), ('HLC3', 'HLC3'), ('OHLC4', 'OHLC4'), ('CURRENT_DAY_OPEN', 'Current Day Open'), ('PREV_WEEK_HIGH', 'Previous Week High'), ('PREV_WEEK_LOW', 'Previous Week Low'), ('CANDLE_PATTERN', 'Candle Pattern'), ('CANDLE_BODY_SIZE', 'Candle Body Size'), ('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('WMA', 'Weighted Moving Average'), ('HMA', 'Hull Moving Average'), ('ALMA', 'Arnaud Legoux Moving Average'), ('KAMA', 'Kaufman Adaptive Moving Average'), ('DEMA', 'Double Exponential Moving Average'), ('TEMA', 'Triple Exponential Moving Average'), ('RSI', 'Relative Strength Index'), ('ROC', 'Rate of Change'), ('MACD', 'MACD'), ('BOLLINGER_BANDS', 'Bollinger Bands'), ('SUPERTREND', 'SuperTrend'), ('ADX', 'Average Directional Index'), ('DMI', 'Directional Movement Index'), ('STOCHASTIC', 'Stochastic'), ('ATR', 'Average True Range'), ('CCI', 'Commodity Channel Index'), ('WILLIAMS_R', 'Williams %R'), ('OBV', 'On Balance Volume'), ('MFI', 'Money Flow Index'), ('PIVOT_POINT', 'Pivot Point'), ('KELTNER_CHANNEL', 'Keltner Channel'), ('DONCHIAN_CHANNEL', 'Donchian Channel'), ('PARABOLIC_SAR', 'Parabolic SAR'), ('ICHIMOKU_CLOUD', 'Ichimoku Cloud'), ('POSITION_PNL_PERCENTAGE', 'Position PnL %'), ('POSITION_PNL_POINTS', 'Position PnL Points'), ('TRAILING_PEAK_OFFSET', 'Trailing Peak Offset'), ('ENTRY_PRICE', 'Entry Price'), ('TIME_DECAY', 'Time Decay Exit'), ('CONSTANT', 'Constant Value'), ('MATH_EXPRESSION', 'Math Expression')], default='CONSTANT', max_length=50),
        ),
    ]
