# Generated by Django 5.2.12 on 2026-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0019_alter_rule_comparison_alter_rule_operand_a_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='comparison',
            field=models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('EQ', 'Equal To'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal'), ('CROSSES_ABOVE', 'Crosses Above'), ('CROSSES_BELOW', 'Crosses Below'), ('NEQ', 'Not Equal To')], default='GT', max_length=20),
        ),
    ]
