# Generated by Django 5.2.12 on 2026-08-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0021_alter_rule_operand_a_type_alter_rule_operand_b_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerule',
            name='candle_completion_rule',
        ),
    ]
