# Generated by Django 5.2.12 on 2026-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0022_remove_timerule_candle_completion_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulegroup',
            name='action',
            field=models.CharField(blank=True, choices=[('EXIT_ALL', 'Exit Full Position'), ('PARTIAL_EXIT', 'Partial Exit'), ('MOVE_TO_BREAKEVEN', 'Move Stop Loss to Breakeven')], max_length=50, null=True),
        ),
    ]
