# Generated by Django 5.2.12 on 2026-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0023_alter_rulegroup_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulegroup',
            name='action',
            field=models.CharField(blank=True, choices=[('EXIT_ALL', 'Exit Full Position'), ('PARTIAL_EXIT', 'Take Partial Profit'), ('MOVE_TO_BREAKEVEN', 'Move SL to Breakeven')], max_length=50, null=True),
        ),
    ]
