# Generated by Django 5.2.12 on 2026-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0025_timerule_builder_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerule',
            name='market_session',
            field=models.CharField(choices=[('MARKET_OPEN', 'Market Open')], default='MARKET_OPEN', help_text='Market session to trade in', max_length=20),
        ),
    ]
