# Generated by Django 5.2.5 on 2025-08-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatatoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
