# Generated by Django 5.2.5 on 2025-08-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_marketdatatoken_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketdatatoken',
            old_name='active',
            new_name='is_active',
        ),
    ]
