# Generated by Django 5.2.5 on 2026-03-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
        ('marketdata', '0003_rename_active_marketdatatoken_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('EARNINGS', 'Earnings'), ('RBI_POLICY', 'RBI Policy'), ('BUDGET', 'Union Budget'), ('GDP', 'GDP Data'), ('INFLATION', 'Inflation Data'), ('FED_DECISION', 'Fed Decision'), ('NEWS', 'News Event'), ('CUSTOM', 'Custom Event')], max_length=32)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('impact', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_events', to='instruments.instrument')),
            ],
            options={
                'ordering': ['event_date', 'event_time', 'title'],
                'indexes': [models.Index(fields=['event_type', 'event_date'], name='marketdata__event_t_e82e4c_idx'), models.Index(fields=['event_date'], name='marketdata__event_d_98bc83_idx')],
            },
        ),
    ]
