# Generated by Django 5.2.12 on 2026-04-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
        ('marketdata', '0004_marketevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('timeframe', models.CharField(db_index=True, default='1m', max_length=10)),
                ('time', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('volume', models.BigIntegerField(default=0)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to='instruments.instrument')),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-time'], name='marketdata__symbol_51f687_idx'), models.Index(fields=['timeframe', '-time'], name='marketdata__timefra_5e746a_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe', 'time'), name='unique_candle_symbol_timeframe_time')],
            },
        ),
    ]
