# Generated by Django 5.2.5 on 2025-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_account_order_tradehistory_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='unrealized_pnl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='position',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='trading.instrument'),
        ),
    ]
