# Generated by Django 5.2.12 on 2026-04-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
        ('trading', '0003_account_realized_pnl_account_unrealized_pnl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='order',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='trading_watchlists', to='instruments.instrument'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
