# Generated by Django 5.2.12 on 2026-07-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_position_instrument_alter_order_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_oco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='oco_linked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_to', to='trading.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='position_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_orders', to='trading.position'),
        ),
    ]
