# Generated by Django 5.2.12 on 2026-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_alter_instrument_exchange'),
        ('trading', '0006_position_created_at_alter_order_position_link_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='closedpositionlog',
            index=models.Index(fields=['account', '-exit_time'], name='terminal_close_time_idx'),
        ),
    ]
