# Generated by Django 5.2.12 on 2026-04-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0003_brokerfundssnapshot'),
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PLACED', 'Placed'), ('ACKNOWLEDGED', 'Acknowledged'), ('PARTIAL_FILL', 'Partial Fill'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('MODIFIED', 'Modified'), ('EXPIRED', 'Expired'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('fill_quantity', models.PositiveIntegerField(default=0)),
                ('fill_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'live_execution_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('STRATEGY', 'Strategy'), ('EXTERNAL', 'External / Manual'), ('RECOVERED', 'Recovered')], default='STRATEGY', max_length=20)),
                ('product_type', models.CharField(choices=[('CNC', 'Cash and Carry (Equity delivery)'), ('INTRADAY', 'Intraday (All segments)'), ('MARGIN', 'Margin (Derivatives only)'), ('CO', 'Cover Order'), ('BO', 'Bracket Order'), ('MTF', 'Margin Trading Facility')], default='INTRADAY', max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('day_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_broker_sync', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_position',
            },
        ),
        migrations.CreateModel(
            name='LiveStrategyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Capital'), ('FIXED', 'Fixed Amount')], default='FIXED', max_length=20)),
                ('allocated_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reserved_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('broker_equity_reference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_over_allocated', models.BooleanField(default=False)),
                ('breach_reason', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'live_strategy_allocation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SlippageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('slippage_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('slippage_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('market_impact', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'live_slippage_record',
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='PAUSED', max_length=20)),
                ('trades_count', models.PositiveIntegerField(default=0)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'live_trading_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=128)),
                ('exchange_order_id', models.CharField(blank=True, max_length=128)),
                ('source_type', models.CharField(choices=[('STRATEGY', 'Strategy'), ('EXTERNAL', 'External / Manual'), ('RECOVERED', 'Recovered')], default='STRATEGY', max_length=20)),
                ('reduce_only', models.BooleanField(default=False)),
                ('requested_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP_LIMIT', 'Stop Limit Order'), ('STOP_MARKET', 'Stop Market Order')], default='MARKET', max_length=20)),
                ('product_type', models.CharField(choices=[('CNC', 'Cash and Carry (Equity delivery)'), ('INTRADAY', 'Intraday (All segments)'), ('MARGIN', 'Margin (Derivatives only)'), ('CO', 'Cover Order'), ('BO', 'Bracket Order'), ('MTF', 'Margin Trading Facility')], default='INTRADAY', max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('filled_quantity', models.PositiveIntegerField(default=0)),
                ('pending_quantity', models.PositiveIntegerField(default=0)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('PARTIAL_FILL', 'Partially Filled'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_code', models.CharField(blank=True, max_length=32)),
                ('validity', models.CharField(choices=[('DAY', 'Day'), ('IOC', 'Immediate or Cancel'), ('GTC', 'Good Till Cancelled')], default='DAY', max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('broker_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='brokers.brokercredential')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_orders', to='instruments.instrument')),
            ],
            options={
                'db_table': 'live_order',
                'ordering': ['-placed_at'],
            },
        ),
    ]
