# Generated by Django 5.2.12 on 2026-04-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0003_brokerfundssnapshot'),
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
        ('live_trading', '0001_initial'),
        ('paper_trading', '0001_initial'),
        ('strategies', '0014_add_entry_side_to_entryorderconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveorder',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='paper_trading.portfolio'),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='live_trading.liveorder'),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='broker_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_positions', to='brokers.brokercredential'),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_positions', to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_positions', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestrategyallocation',
            name='broker_credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_allocations', to='brokers.brokercredential'),
        ),
        migrations.AddField(
            model_name='livestrategyallocation',
            name='capital_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_strategy_allocations', to='paper_trading.capitalallocation'),
        ),
        migrations.AddField(
            model_name='livestrategyallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_allocations', to='paper_trading.portfolio'),
        ),
        migrations.AddField(
            model_name='livestrategyallocation',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_allocations', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='livestrategyallocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_strategy_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='live_trading.livestrategyallocation'),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='live_trading.livestrategyallocation'),
        ),
        migrations.AddField(
            model_name='slippagerecord',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slippage_record', to='live_trading.liveorder'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='broker_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='brokers.brokercredential'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='live_trading.tradingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='livestrategyallocation',
            unique_together={('user', 'strategy', 'broker_credential')},
        ),
        migrations.AlterUniqueTogether(
            name='liveposition',
            unique_together={('user', 'strategy', 'broker_credential', 'instrument', 'side')},
        ),
    ]
