# Generated by Django 5.2.12 on 2026-06-09 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_live_portfolio(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    LivePortfolio = apps.get_model('live_trading', 'LivePortfolio')
    LiveStrategyAllocation = apps.get_model('live_trading', 'LiveStrategyAllocation')
    LiveOrder = apps.get_model('live_trading', 'LiveOrder')

    # Create a LivePortfolio for each user that has live allocations or orders
    user_ids = set(LiveStrategyAllocation.objects.values_list('user_id', flat=True)) | \
               set(LiveOrder.objects.values_list('user_id', flat=True))

    portfolio_map = {}
    for uid in user_ids:
        # Avoid get_or_create to prevent multiple objects returned if duplicates exist somehow
        p, created = LivePortfolio.objects.get_or_create(user_id=uid)
        portfolio_map[uid] = p.id

    # Temporarily drop constraint logic by setting the ID directly.
    # Wait, if we just update the portfolio_id to the new LivePortfolio ID,
    # the constraint will pass when the AlterField executes.
    for alloc in LiveStrategyAllocation.objects.all():
        alloc.portfolio_id = portfolio_map.get(alloc.user_id)
        alloc.save(update_fields=['portfolio_id'])

    for order in LiveOrder.objects.all():
        order.portfolio_id = portfolio_map.get(order.user_id)
        order.save(update_fields=['portfolio_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestrategyallocation',
            name='capital_allocation',
        ),
        migrations.CreateModel(
            name='LivePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Live Portfolio', max_length=100)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invested_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('peak_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('peak_date', models.DateField(blank=True, null=True)),
                ('today_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('today_trades', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Portfolio',
                'verbose_name_plural': 'Live Portfolios',
                'db_table': 'live_portfolio',
            },
        ),
        migrations.RunPython(populate_live_portfolio),
        migrations.AlterField(
            model_name='liveorder',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_orders', to='live_trading.liveportfolio'),
        ),
        migrations.AlterField(
            model_name='livestrategyallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_allocations', to='live_trading.liveportfolio'),
        ),
    ]
