# Generated by Django 5.2.12 on 2026-08-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0004_add_deployed_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestrategyallocation',
            name='is_active',
        ),
    ]
