# Generated by Django 5.2.12 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_trading", "0005_remove_livestrategyallocation_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingsession",
            name="allocation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="live_trading.livestrategyallocation",
            ),
        ),
    ]