# Generated by Django 5.2.12 on 2026-08-27 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_remove_ordersettings_primary_broker_and_more'),
        ('instruments', '0009_remove_executionroute_risk_per_trade_amount'),
        ('live_trading', '0007_backfill_session_allocations'),
        ('strategies', '0020_alter_entryorderconfig_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_time', models.DateTimeField()),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_time', models.DateTimeField()),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='live_trading.livestrategyallocation')),
                ('broker_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_trades', to='brokers.brokercredential')),
                ('exit_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_trades', to='live_trading.liveorder')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to='instruments.instrument')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_trades', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_trade',
                'ordering': ['-exit_time'],
            },
        ),
    ]
