# Generated by Django 5.2.12 on 2026-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0008_livetrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PLACED', 'Placed'), ('ACKNOWLEDGED', 'Acknowledged'), ('PARTIAL_FILL', 'Partial Fill'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('MODIFIED', 'Modified'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], max_length=20),
        ),
        migrations.AlterField(
            model_name='liveorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('PARTIAL_FILL', 'Partially Filled'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingsession',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('STOPPING', 'Stopping'), ('ERROR', 'Error')], default='PAUSED', max_length=20),
        ),
    ]
