# Generated by Django 5.2.12 on 2026-08-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0010_remove_liveportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveposition',
            name='realized_pnl',
        ),
    ]
