# Generated by Django 5.2.12 on 2026-08-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0011_remove_liveposition_realized_pnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveorder',
            name='rejection_code',
        ),
        migrations.RemoveField(
            model_name='liveorder',
            name='trigger_price',
        ),
    ]
