# Generated by Django 5.2.12 on 2026-08-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0012_remove_liveorder_rejection_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveposition',
            name='day_pnl',
        ),
    ]
