# Generated by Django 5.2.12 on 2026-08-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0014_remove_livestrategyallocation_available_capital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveorder',
            name='reduce_only',
        ),
    ]
