# Generated by Django 5.2.12 on 2026-08-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0015_remove_liveorder_reduce_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveorder',
            name='requested_value',
        ),
        migrations.RemoveField(
            model_name='liveorder',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='liveorder',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='liveposition',
            name='source_type',
        ),
    ]
