# Generated by Django 5.2.12 on 2026-08-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0016_remove_liveorder_requested_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='gross_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='holding_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PLACED', 'Placed'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
