# Generated by Django 5.2.12 on 2026-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0017_livetrade_exit_reason_livetrade_gross_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveorder',
            name='last_reconciliation',
            field=models.DateTimeField(blank=True, help_text='Last reconciliation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='reconciliation_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of reconciliation attempts'),
        ),
        migrations.AddField(
            model_name='liveorder',
            name='reconciliation_status',
            field=models.CharField(choices=[('MATCHED', 'Matched'), ('PENDING', 'Pending'), ('MISMATCH', 'Mismatch')], default='PENDING', help_text='Reconciliation status with broker WebSocket', max_length=20),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='broker_position_id',
            field=models.CharField(blank=True, help_text="Broker's position identifier", max_length=128),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync failed'),
        ),
        migrations.AddField(
            model_name='liveposition',
            name='sync_status',
            field=models.CharField(choices=[('SYNCED', 'Synced'), ('PENDING', 'Pending'), ('CONFLICT', 'Conflict')], default='PENDING', help_text='Current sync status with broker', max_length=20),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PLACED', 'Placed'), ('PARTIAL_FILL', 'Partial Fill'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
    ]
