# Generated by Django 5.2.12 on 2026-09-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0021_liveorder_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionlog',
            name='fill_price',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='fill_quantity',
        ),
    ]
