# Generated by Django 5.2.12 on 2026-10-05 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0007_refactor_broker_models'),
        ('instruments', '0010_alter_instrument_exchange'),
        ('live_trading', '0022_remove_executionlog_fill_price_and_more'),
        ('strategies', '0023_alter_strategy_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='livetrade',
            index=models.Index(fields=['user', '-exit_time'], name='live_close_time_idx'),
        ),
    ]
