# Generated by Django 5.2.12 on 2026-04-04 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0013_remove_entryorderconfig_capital_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_free', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('min_capital_required', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expected_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('backtest_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('live_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='strategies.strategy')),
            ],
            options={
                'db_table': 'marketplace_listing',
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_id', models.CharField(blank=True, max_length=120)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='marketplace.marketplacelisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_subscription',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='CreatorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_earnings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='marketplace.marketplacelisting')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_records', to='marketplace.subscription')),
            ],
            options={
                'db_table': 'creator_earning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('use_duration_days', models.PositiveIntegerField(default=0)),
                ('would_recommend', models.BooleanField(default=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.marketplacelisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strategy_review',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
