# Generated by Django 5.2.12 on 2026-07-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('NFO', 'NSE Futures & Options'), ('MCX', 'Multi Commodity Exchange'), ('CDS', 'Currency Derivatives'), ('BFO', 'BSE Futures & Options')], help_text='Exchange identifier (e.g., NSE, BSE, MCX)', max_length=10, unique=True)),
                ('market_open', models.TimeField(help_text='Regular market open time (e.g., 09:15 for NSE)')),
                ('market_close', models.TimeField(help_text='Regular market close time (e.g., 15:30 for NSE)')),
                ('pre_market_open', models.TimeField(blank=True, help_text='Pre-market session open time', null=True)),
                ('pre_market_close', models.TimeField(blank=True, help_text='Pre-market session close time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exchange is currently active')),
            ],
            options={
                'verbose_name': 'Exchange Configuration',
                'verbose_name_plural': 'Exchange Configurations',
                'db_table': 'exchange_configs',
                'ordering': ['exchange'],
            },
        ),
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Holiday date')),
                ('description', models.CharField(help_text='Holiday name/description (e.g., "Republic Day", "Diwali")', max_length=200)),
                ('is_partial', models.BooleanField(default=False, help_text='If True, market has shortened hours on this date')),
                ('partial_close', models.TimeField(blank=True, help_text='Early close time for partial trading days', null=True)),
                ('exchange', models.ForeignKey(help_text='Exchange this holiday applies to', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='common.exchangeconfig')),
            ],
            options={
                'verbose_name': 'Market Holiday',
                'verbose_name_plural': 'Market Holidays',
                'db_table': 'market_holidays',
                'ordering': ['-date'],
                'unique_together': {('exchange', 'date')},
            },
        ),
    ]
