# Generated by Django 5.2.12 on 2026-09-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seed_exchange_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfig',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('MCX', 'Multi Commodity Exchange')], help_text='Exchange identifier (e.g., NSE, BSE, MCX)', max_length=10, unique=True),
        ),
    ]
