# Generated by Django 5.2.12 on 2026-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_exchangeconfig_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconfig',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA timezone used for exchange sessions (e.g., Asia/Kolkata)', max_length=64),
        ),
    ]
