# Generated by Django 5.2.12 on 2026-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_exchangeconfig_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfig',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata (IST)'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York (EST/EDT)'), ('Europe/London', 'Europe/London (GMT/BST)'), ('Asia/Tokyo', 'Asia/Tokyo (JST)'), ('Australia/Sydney', 'Australia/Sydney (AEST/AEDT)')], default='Asia/Kolkata', help_text='IANA timezone used for exchange sessions (e.g., Asia/Kolkata)', max_length=64),
        ),
    ]
