# Generated by Django 5.2.12 on 2026-04-04 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0004_backtestmetrics_avg_mae_backtestmetrics_avg_mfe_and_more'),
        ('instruments', '0003_alter_optioncontract_unique_together_and_more'),
        ('strategies', '0013_remove_entryorderconfig_capital_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('RULE_SUGGESTION', 'Rule Suggestion'), ('PARAMETER_TUNING', 'Parameter Tuning'), ('OVERFIT_WARNING', 'Overfit Warning'), ('REGIME_CHANGE', 'Regime Change'), ('RISK_ALERT', 'Risk Alert')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(default='1D', max_length=10)),
                ('regime_type', models.CharField(choices=[('TRENDING', 'Trending'), ('RANGING', 'Ranging'), ('HIGH_VOLATILITY', 'High Volatility'), ('LOW_VOLATILITY', 'Low Volatility'), ('BREAKOUT', 'Breakout')], max_length=20)),
                ('direction', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('strength', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_regimes', to='instruments.instrument')),
            ],
            options={
                'db_table': 'market_regime',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='OverfitDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overfit_probability', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('in_sample_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('out_sample_sharpe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('degradation_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overfit_detections', to='backtesting.backtestrun')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overfit_detections', to='strategies.strategy')),
            ],
            options={
                'db_table': 'overfit_detection',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('execution_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='strategies.strategy')),
            ],
            options={
                'db_table': 'strategy_health_score',
                'ordering': ['-date'],
                'unique_together': {('strategy', 'date')},
            },
        ),
    ]
