# Generated by Django 5.2.12 on 2026-04-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_trading', '0002_initial'),
        ('paper_trading', '0001_initial'),
        ('strategies', '0014_add_entry_side_to_entryorderconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('RISK', 'Risk'), ('PSYCHOLOGY', 'Psychology')], default='RISK', max_length=20)),
            ],
            options={
                'db_table': 'journal_mistake_tag',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('emotion_before', models.CharField(blank=True, max_length=60)),
                ('emotion_after', models.CharField(blank=True, max_length=60)),
                ('setup_quality', models.PositiveIntegerField(default=3)),
                ('execution_quality', models.PositiveIntegerField(default=3)),
                ('rule_followed', models.BooleanField(default=True)),
                ('mistake_tags', models.JSONField(blank=True, default=list)),
                ('lessons_learned', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('screenshot_urls', models.JSONField(blank=True, default=list)),
                ('chart_snapshot_url', models.URLField(blank=True)),
                ('live_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='live_trading.liveorder')),
                ('paper_trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='paper_trading.papertrade')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('related_trades', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_insight',
                'ordering': ['-generated_at'],
            },
        ),
    ]
