# Generated by Django 5.2.12 on 2026-10-06 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_unlinked_reviews(apps, schema_editor):
    JournalEntry = apps.get_model('trade_journal', 'JournalEntry')
    JournalEntry.objects.using(schema_editor.connection.alias).filter(
        terminal_trade__isnull=True, paper_trade__isnull=True, live_trade__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0023_livetrade_live_close_time_idx'),
        ('paper_trading', '0014_papertrade_paper_close_time_idx'),
        ('trade_journal', '0002_execution_reviews'),
        ('trading', '0007_closedpositionlog_terminal_close_time_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_unlinked_reviews),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='journal_source_matches_trade',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='live_trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='live_trading.livetrade'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='paper_trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='paper_trading.papertrade'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='terminal_trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='trading.closedpositionlog'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('live_trade__isnull', True), ('paper_trade__isnull', True), ('source', 'TERMINAL'), ('terminal_trade__isnull', False)), models.Q(('live_trade__isnull', True), ('paper_trade__isnull', False), ('source', 'PAPER'), ('terminal_trade__isnull', True)), models.Q(('live_trade__isnull', False), ('paper_trade__isnull', True), ('source', 'LIVE'), ('terminal_trade__isnull', True)), _connector='OR'), name='journal_source_matches_trade'),
        ),
    ]
