# Generated by Django 5.2.5 on 2026-01-15 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('strategy_type', models.CharField(choices=[('INTRADAY', 'Intraday'), ('POSITIONAL', 'Positional'), ('SWING', 'Swing'), ('SCALPING', 'Scalping')], default='INTRADAY', max_length=20)),
                ('market_type', models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURES', 'Futures'), ('OPTIONS', 'Options'), ('FOREX', 'Forex'), ('CRYPTO', 'Crypto')], default='EQUITY', max_length=20)),
                ('exchange', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('NFO', 'NSE Futures & Options'), ('BFO', 'BSE Futures & Options'), ('MCX', 'Multi Commodity Exchange'), ('CDS', 'Currency Derivatives'), ('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], default='NSE', max_length=20)),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('FUTURE', 'Future'), ('OPTION', 'Option Contract'), ('CURRENCY', 'Currency Pair'), ('COMMODITY', 'Commodity')], default='STOCK', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('MARKETPLACE', 'Marketplace')], default='PRIVATE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paper_trading_enabled', models.BooleanField(default=True)),
                ('live_trading_enabled', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_strategies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='strategies', to='strategies.strategytag')),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReEntryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_reentry', models.BooleanField(default=True)),
                ('max_reentries', models.PositiveIntegerField(default=2, help_text='Maximum re-entries per trading session')),
                ('reentry_cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Minimum seconds before re-entry')),
                ('allow_reverse_entry', models.BooleanField(default=False, help_text='Allow reversing position on opposite signal')),
                ('require_trend_confirmation', models.BooleanField(default=False)),
                ('trend_indicator', models.CharField(blank=True, help_text='Indicator for trend confirmation (e.g., EMA_50)', max_length=50, null=True)),
                ('trend_params', models.JSONField(blank=True, help_text='Parameters for trend indicator', null=True)),
                ('loss_recovery_mode', models.BooleanField(default=False, help_text='Increase position size after loss')),
                ('loss_recovery_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for position size after loss', max_digits=4)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reentry_rule', to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP_LIMIT', 'Stop Limit Order'), ('STOP_MARKET', 'Stop Market Order')], default='MARKET', max_length=20)),
                ('entry_price_logic', models.CharField(choices=[('AT_CLOSE', 'At Candle Close'), ('AT_BREAKOUT', 'At Breakout Price'), ('OFFSET', 'Offset from Price')], default='AT_CLOSE', max_length=20)),
                ('price_offset', models.DecimalField(decimal_places=2, default=0, help_text='Offset from signal price (positive for above, negative for below)', max_digits=10)),
                ('quantity_type', models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_BASED', 'Risk Based')], default='FIXED', max_length=20)),
                ('fixed_quantity', models.PositiveIntegerField(default=1)),
                ('capital_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of allocated capital per trade', max_digits=5)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed risk amount per trade', max_digits=10, null=True)),
                ('slippage_tolerance_pct', models.DecimalField(decimal_places=2, default=0.1, help_text='Maximum allowed slippage percentage', max_digits=5)),
                ('allow_partial_entry', models.BooleanField(default=False)),
                ('scaling_levels', models.JSONField(blank=True, help_text='Scaling in levels: [{pct: 50, at_price_pct: -1}, ...]', null=True)),
                ('entry_cooldown_seconds', models.PositiveIntegerField(default=0, help_text='Minimum seconds between entries')),
                ('max_entry_attempts', models.PositiveIntegerField(default=3, help_text='Maximum order placement attempts')),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_order_config', to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('config_snapshot', models.JSONField(help_text='Complete strategy configuration at this version')),
                ('change_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['user', 'status'], name='strategies__user_id_4fa271_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['visibility'], name='strategies__visibil_9bb89e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyversion',
            unique_together={('strategy', 'version_number')},
        ),
    ]
