# Generated by Django 5.2.5 on 2026-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='allow_backtest',
            field=models.BooleanField(default=False, help_text='Allow other users to backtest this strategy'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='allow_clone',
            field=models.BooleanField(default=False, help_text='Allow other users to clone this strategy'),
        ),
    ]
