# Generated by Django 5.2.5 on 2026-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_strategy_allow_backtest_strategy_allow_clone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryorderconfig',
            name='max_daily_trades',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of trades per day'),
        ),
        migrations.AddField(
            model_name='entryorderconfig',
            name='max_positions',
            field=models.PositiveIntegerField(default=5, help_text='Maximum open positions at any time'),
        ),
        migrations.AddField(
            model_name='entryorderconfig',
            name='risk_per_trade_pct',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Maximum risk per trade as percentage of capital', max_digits=5),
        ),
    ]
