# Generated by Django 5.2.5 on 2026-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_alter_strategy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryorderconfig',
            name='entry_group_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', help_text='Logic for combining multiple entry groups (e.g., Group A OR Group B)', max_length=10),
        ),
        migrations.AlterField(
            model_name='entryorderconfig',
            name='quantity_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('CAPITAL_BASED', 'Capital Based'), ('RISK_FIXED', 'Risk Based (Fixed Amount)'), ('RISK_PERCENTAGE', 'Risk Based (% of Capital)')], default='FIXED', max_length=20),
        ),
    ]
