# Generated by Django 5.2.5 on 2026-02-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_entryorderconfig_entry_group_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_loss_group_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', help_text='Logic for combining multiple stop loss groups', max_length=10)),
                ('target_group_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', help_text='Logic for combining multiple target groups', max_length=10)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_order_config', to='strategies.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
