# Generated by Django 5.2.5 on 2026-02-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_exitorderconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reentryrule',
            name='require_trend_confirmation',
        ),
        migrations.RemoveField(
            model_name='reentryrule',
            name='trend_indicator',
        ),
        migrations.RemoveField(
            model_name='reentryrule',
            name='trend_params',
        ),
    ]
