# Generated by Django 5.2.5 on 2026-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_remove_reentryrule_require_trend_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryorderconfig',
            name='capital_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Percentage of allocated capital per trade', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='entryorderconfig',
            name='fixed_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='entryorderconfig',
            name='price_offset',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Offset from signal price (positive for above, negative for below)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entryorderconfig',
            name='risk_per_trade_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Maximum risk per trade as percentage of capital', max_digits=5, null=True),
        ),
    ]
