# Generated by Django 5.2.5 on 2026-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_alter_entryorderconfig_capital_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='auto_version_enabled',
            field=models.BooleanField(default=True, help_text='If true, versions are automatically created on save.'),
        ),
    ]
