# Generated by Django 5.2.5 on 2026-02-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_strategy_auto_version_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='auto_version_enabled',
            field=models.BooleanField(default=False, help_text='If true, versions are automatically created on save.'),
        ),
    ]
