# Generated by Django 5.2.5 on 2026-02-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_alter_strategy_auto_version_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='scaling_levels',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='is_approved',
        ),
    ]
