# Generated by Django 5.2.5 on 2026-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0011_remove_entryorderconfig_scaling_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('MCX', 'Multi Commodity Exchange'), ('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], default='NSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='instrument_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('INDEX', 'Index'), ('FUTURE', 'Future'), ('OPTION', 'Option Contract'), ('CURRENCY', 'Currency Pair'), ('COMMODITY', 'Commodity'), ('ETF', 'Exchange Traded Fund'), ('BOND', 'Bond / Govt Securities'), ('MF', 'Mutual Fund')], default='STOCK', max_length=20),
        ),
    ]
