# Generated by Django 5.2.5 on 2026-02-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0012_alter_strategy_exchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='capital_percentage',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='fixed_quantity',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='max_daily_trades',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='max_positions',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='quantity_type',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='risk_amount',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='risk_per_trade_pct',
        ),
    ]
