# Generated by Django 5.2.12 on 2026-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0013_remove_entryorderconfig_capital_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryorderconfig',
            name='entry_side',
            field=models.CharField(choices=[('BUY', 'Buy / Long'), ('SELL', 'Sell / Short')], default='BUY', help_text='Trade direction: BUY for Long entries, SELL for Short entries', max_length=10),
        ),
    ]
