# Generated by Django 5.2.12 on 2026-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0014_add_entry_side_to_entryorderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryorderconfig',
            name='entry_price_logic',
            field=models.CharField(choices=[('LTP', 'Last Traded Price (Instant)'), ('AT_CLOSE', 'At Close'), ('AT_OPEN', 'At Next Open'), ('ABOVE_HIGH', 'Above High'), ('BELOW_LOW', 'Below Low'), ('AT_BREAKOUT', 'At Breakout'), ('OFFSET', 'Limit with Offset')], default='AT_CLOSE', max_length=20),
        ),
    ]
