# Generated by Codex on 2026-05-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0015_alter_entryorderconfig_entry_price_logic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entryorderconfig",
            name="max_entry_attempts",
        ),
        migrations.RemoveField(
            model_name="entryorderconfig",
            name="slippage_tolerance_pct",
        ),
    ]
