# Generated by Django 5.2.12 on 2026-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0016_remove_unused_entry_execution_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='entry_price_logic',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='reentryrule',
            name='loss_recovery_mode',
        ),
        migrations.RemoveField(
            model_name='reentryrule',
            name='loss_recovery_multiplier',
        ),
        migrations.RemoveField(
            model_name='reentryrule',
            name='max_reentries',
        ),
        migrations.AddField(
            model_name='entryorderconfig',
            name='execution_style',
            field=models.CharField(choices=[('LTP', 'Market (Instant)'), ('MARKET_AT_CLOSE', 'Market at Close'), ('LIMIT_OFFSET', 'Limit with Offset'), ('STOP_BREAKOUT', 'Stop at Breakout'), ('AT_OPEN', 'Market at Next Open')], default='LTP', help_text='Unified entry logic (e.g. Market at Close, Limit with Offset)', max_length=20),
        ),
        migrations.AddField(
            model_name='exitorderconfig',
            name='exit_group_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', help_text='Logic for combining multiple exit rules', max_length=10),
        ),
    ]
