# Generated by Django 5.2.12 on 2026-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0017_remove_entryorderconfig_entry_price_logic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
