# Generated by Django 5.2.12 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0018_alter_strategy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='allow_partial_entry',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='entry_cooldown_seconds',
        ),
        migrations.RemoveField(
            model_name='entryorderconfig',
            name='execution_style',
        ),
        migrations.AddField(
            model_name='entryorderconfig',
            name='cooldown_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Minimum seconds between any trade entries on this instrument'),
        ),
        migrations.AddField(
            model_name='entryorderconfig',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP_LIMIT', 'Stop Limit Order'), ('STOP_MARKET', 'Stop Market Order')], default='MARKET', help_text='Order type to place on entry signal (MARKET or LIMIT)', max_length=20),
        ),
        migrations.AlterField(
            model_name='entryorderconfig',
            name='entry_side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', help_text='Trade direction: BUY for Long entries, SELL for Short entries', max_length=4),
        ),
        migrations.AlterField(
            model_name='entryorderconfig',
            name='price_offset',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Limit price offset from signal close price', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ReEntryRule',
        ),
    ]
