# Generated by Django 5.2.12 on 2026-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0019_remove_entryorderconfig_allow_partial_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryorderconfig',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP_LIMIT', 'Stop Limit Order'), ('STOP_MARKET', 'Stop Market Order')], default='MARKET', help_text='Order type to place on entry signal (MARKET)', max_length=20),
        ),
    ]
