# Generated by Django 5.2.12 on 2026-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0020_alter_entryorderconfig_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('MCX', 'Multi Commodity Exchange')], default='NSE', max_length=20),
        ),
    ]
