# Generated by Django 5.2.12 on 2026-10-05 19:01

from django.db import migrations, models


def make_retired_listings_private(apps, schema_editor):
    apps.get_model('strategies', 'Strategy').objects.using(schema_editor.connection.alias).filter(visibility='MARKETPLACE').update(visibility='PRIVATE')


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0022_alter_strategy_status'),
    ]

    operations = [
        migrations.RunPython(make_retired_listings_private),
        migrations.AlterField(
            model_name='strategy',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20),
        ),
    ]
