# Generated by Django 5.2.12 on 2026-10-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0023_alter_strategy_visibility'),
        ('risk_management', '0013_remove_positionsizingrule_risk_per_trade_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='allow_backtest',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='allow_clone',
        ),
    ]
