# Generated by Django 5.2.12 on 2026-05-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('COMMUNITY', 'Community'), ('LEARNING', 'Learning'), ('DISCIPLINE', 'Discipline'), ('TRADING', 'Trading'), ('CREATOR', 'Creator'), ('VERIFICATION', 'Verification')], max_length=30)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=80)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gamification_achievement',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AntiGamingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gamification_anti_gaming_rule',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('MARKET_REPLAY', 'Market Replay'), ('CRASH_SURVIVAL', 'Crash Survival'), ('LOW_CAPITAL', 'Low Capital'), ('PROP_FIRM', 'Prop Firm'), ('NEWS_EVENT', 'News Event'), ('DRAWDOWN_DISCIPLINE', 'Drawdown Discipline'), ('RISK_ONLY', 'Risk Only')], max_length=40)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gamification_challenge',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XPGrantLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=80, unique=True)),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('min_quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gamification_xp_grant_limit',
            },
        ),
        migrations.CreateModel(
            name='UserTrustFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_type', models.CharField(choices=[('XP_FARMING', 'XP Farming'), ('BOT_BEHAVIOR', 'Bot Behavior'), ('FAKE_CLAIM', 'Fake Claim'), ('LOW_QUALITY', 'Low Quality'), ('MANUAL_REVIEW', 'Manual Review')], max_length=40)),
                ('severity', models.CharField(default='WARNING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_trust_flag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXPBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('weekly_xp', models.IntegerField(default=0)),
                ('monthly_xp', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_xp_balance',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('JOINED', 'Joined'), ('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='JOINED', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_challenge_participant',
                'ordering': ['-updated_at'],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('OVERALL', 'Overall'), ('COMMUNITY_HELPFULNESS', 'Community Helpfulness'), ('LEARNING_XP', 'Learning XP'), ('JOURNAL_DISCIPLINE', 'Journal Discipline'), ('PAPER_PERFORMANCE', 'Paper Performance'), ('RISK_DISCIPLINE', 'Risk Discipline'), ('CREATOR_REPUTATION', 'Creator Reputation'), ('VERIFIED_TRADER_SCORE', 'Verified Trader Score')], max_length=40)),
                ('scope', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ALL_TIME', 'All Time')], default='WEEKLY', max_length=20)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('eligible', models.BooleanField(default=True)),
                ('snapshot_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_leaderboard_snapshot',
                'ordering': ['category', 'scope', 'rank'],
                'unique_together': {('user', 'category', 'scope', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streak_type', models.CharField(choices=[('JOURNAL', 'Journal'), ('LEARNING', 'Learning'), ('RULE_DISCIPLINE', 'Rule Discipline'), ('PAPER_TRADING', 'Paper Trading'), ('COMMUNITY_HELPFULNESS', 'Community Helpfulness')], max_length=40)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('longest_count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('freeze_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_streak',
                'unique_together': {('user', 'streak_type')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_awards', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_achievement',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('points', models.IntegerField()),
                ('quality_score', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_xp_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source_type', 'created_at'], name='gamificatio_user_id_8d01de_idx')],
            },
        ),
    ]
