# Generated by Django 5.2.12 on 2026-07-25 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='jti',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Constant Session Identifier', unique=True),
        ),
    ]
