# Generated by Django 5.2.12 on 2026-04-04 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_name', models.CharField(choices=[('ZERODHA', 'Zerodha'), ('ANGEL', 'Angel Broking'), ('FYERS', 'Fyers'), ('UPSTOX', 'Upstox'), ('IIFL', 'IIFL Securities'), ('ICICI', 'ICICI Direct'), ('HDFC', 'HDFC Securities'), ('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('client_id', models.CharField(max_length=120)),
                ('api_key', models.TextField(blank=True)),
                ('api_secret', models.TextField(blank=True)),
                ('totp_secret', models.CharField(blank=True, max_length=128)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_credential',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'broker_name', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='BrokerAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='brokers.brokercredential')),
            ],
            options={
                'db_table': 'broker_api_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='brokers.brokercredential')),
            ],
            options={
                'db_table': 'broker_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_order_id', models.CharField(max_length=128)),
                ('internal_order_id', models.CharField(max_length=128)),
                ('broker_status', models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('PARTIAL_FILL', 'Partially Filled'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20)),
                ('internal_status', models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('PARTIAL_FILL', 'Partially Filled'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20)),
                ('discrepancy_type', models.CharField(blank=True, max_length=80)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_order_reconciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_slippage_pct', models.DecimalField(decimal_places=3, default=0.1, max_digits=6)),
                ('order_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('retry_delay_ms', models.PositiveIntegerField(default=500)),
                ('partial_fill_action', models.CharField(choices=[('ACCEPT', 'Accept Partial Fill'), ('CANCEL_REMAINING', 'Cancel Remaining Quantity'), ('RETRY_REMAINING', 'Retry Remaining Quantity')], default='ACCEPT', max_length=20)),
                ('use_amo_orders', models.BooleanField(default=False)),
                ('prefer_limit_orders', models.BooleanField(default=False)),
                ('primary_broker', models.CharField(choices=[('ZERODHA', 'Zerodha'), ('ANGEL', 'Angel Broking'), ('FYERS', 'Fyers'), ('UPSTOX', 'Upstox'), ('IIFL', 'IIFL Securities'), ('ICICI', 'ICICI Direct'), ('HDFC', 'HDFC Securities'), ('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], default='FYERS', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_order_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_order_settings',
            },
        ),
    ]
