# Generated by Django 5.2.12 on 2026-04-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersettings',
            name='prefer_limit_orders',
        ),
    ]
