# Generated by Django 5.2.12 on 2026-04-26 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_remove_ordersettings_prefer_limit_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerFundsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('used_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('collateral', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withdrawable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_snapshots', to='brokers.brokercredential')),
            ],
            options={
                'db_table': 'broker_funds_snapshot',
                'ordering': ['-snapshot_time', '-created_at'],
            },
        ),
    ]
