# Generated by Django 5.2.12 on 2026-07-25 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_brokerfundssnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerChargeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name (e.g., "Zerodha Equity", "Fyers F&O")', max_length=100)),
                ('brokerage_per_order', models.DecimalField(decimal_places=2, default=20, help_text='Flat brokerage per executed order in INR', max_digits=10)),
                ('brokerage_pct', models.DecimalField(decimal_places=4, default=0.03, help_text='Brokerage as percentage of turnover (e.g., 0.03 = 0.03%)', max_digits=6)),
                ('brokerage_cap', models.DecimalField(decimal_places=2, default=20, help_text='Maximum brokerage per order in INR (cap)', max_digits=10)),
                ('stt_eq_delivery_pct', models.DecimalField(decimal_places=4, default=0.1, help_text='STT on equity delivery (buy + sell) as % of turnover', max_digits=6)),
                ('stt_eq_intraday_pct', models.DecimalField(decimal_places=4, default=0.025, help_text='STT on equity intraday (sell side only) as % of turnover', max_digits=6)),
                ('stt_futures_pct', models.DecimalField(decimal_places=4, default=0.02, help_text='STT on futures (sell side only) as % of turnover', max_digits=6)),
                ('stt_options_sell_pct', models.DecimalField(decimal_places=4, default=0.1, help_text='STT on options (sell side, on premium) as % of turnover', max_digits=6)),
                ('exchange_txn_pct', models.DecimalField(decimal_places=6, default=0.00345, help_text='Exchange transaction charge for equity as % of turnover', max_digits=8)),
                ('exchange_txn_fo_pct', models.DecimalField(decimal_places=6, default=0.05, help_text='Exchange transaction charge for F&O as % of turnover', max_digits=8)),
                ('sebi_turnover_pct', models.DecimalField(decimal_places=8, default=0.0001, help_text='SEBI turnover fee as % of turnover', max_digits=10)),
                ('stamp_duty_pct', models.DecimalField(decimal_places=4, default=0.003, help_text='Stamp duty on buy side as % of turnover', max_digits=6)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage applied on brokerage + exchange charges', max_digits=5)),
                ('is_default', models.BooleanField(default=False, help_text='If True, this profile is used by default for new backtests/paper trades')),
                ('broker_credential', models.ForeignKey(blank=True, help_text='Optional link to a specific broker credential', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_profiles', to='brokers.brokercredential')),
                ('user', models.ForeignKey(help_text='Owner of this charge profile', on_delete=django.db.models.deletion.CASCADE, related_name='charge_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_charge_profiles',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
