# Generated by Django 5.2.12 on 2026-08-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_seed_default_charge_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersettings',
            name='primary_broker',
        ),
        migrations.RemoveField(
            model_name='ordersettings',
            name='user',
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='broker_credential',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_settings', to='brokers.brokercredential'),
        ),
        migrations.AlterField(
            model_name='brokercredential',
            name='broker_name',
            field=models.CharField(choices=[('ZERODHA', 'Zerodha'), ('ANGEL', 'Angel Broking'), ('FYERS', 'Fyers'), ('UPSTOX', 'Upstox'), ('IIFL', 'IIFL Securities'), ('ICICI', 'ICICI Direct'), ('HDFC', 'HDFC Securities')], max_length=20),
        ),
    ]
