# Generated by Django 5.2.12 on 2026-10-05 18:28

from django.conf import settings
from django.db import migrations, models


def sanitize_history(apps, schema_editor):
    # Frozen allowlists deliberately exclude credentials, tokens and session identifiers.
    safe = {
        'Strategy': {'name', 'status', 'visibility', 'strategy_type', 'market_type', 'exchange', 'instrument_type',
                     'paper_trading_enabled', 'live_trading_enabled', 'time_rule', 'special_event_filter',
                     'entry_order_config', 'exit_order_config', 'position_sizing_rule', 'auto_disable_rules',
                     'watchlist_instruments', 'rule_groups'},
        'BrokerCredential': {'broker_name', 'label', 'is_active', 'is_verified'},
        'PaperAccount': {'name', 'current_balance'},
        'CapitalAllocation': {'strategy_id', 'deployed_version_id', 'allocation_type', 'allocated_amount', 'allocated_percentage'},
        'LiveStrategyAllocation': {'strategy_id', 'broker_credential_id', 'deployed_version_id', 'allocation_type', 'allocated_capital', 'allocated_percentage'},
        'PaperTradingSession': {'strategy_id', 'account_id', 'status', 'slippage_pct', 'include_charges', 'charge_profile_id'},
        'TradingSession': {'strategy_id', 'broker_credential_id', 'allocation_id', 'status'},
    }
    Log = apps.get_model('audit', 'AuditLog')
    batch = []
    for record in Log.objects.using(schema_editor.connection.alias).all().iterator(chunk_size=500):
        allowed = safe.get(record.entity_type, set())
        record.old_value = {key: value for key, value in (record.old_value or {}).items() if key in allowed} if isinstance(record.old_value, dict) else {}
        record.new_value = {key: value for key, value in (record.new_value or {}).items() if key in allowed} if isinstance(record.new_value, dict) else {}
        record.actor_name = 'Unknown (historical)'
        if record.entity_type == 'BrokerCredential':
            record.entity_name = f'Broker account #{record.entity_id}'
        batch.append(record)
        if len(batch) == 500:
            Log.objects.using(schema_editor.connection.alias).bulk_update(batch, ['old_value', 'new_value', 'actor_name', 'entity_name'])
            batch.clear()
    if batch:
        Log.objects.using(schema_editor.connection.alias).bulk_update(batch, ['old_value', 'new_value', 'actor_name', 'entity_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancecheck',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategyapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='strategyapproval',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='strategyapproval',
            name='strategy',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_name',
            field=models.CharField(default='System', max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(sanitize_history),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DEPLOY', 'Deploy'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('STOP_REQUESTED', 'Stop Requested'), ('STOP', 'Stop'), ('ALLOCATE', 'Allocate'), ('DEALLOCATE', 'Deallocate'), ('RESET', 'Reset')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_user_time_idx'),
        ),
        migrations.DeleteModel(
            name='ComplianceCheck',
        ),
        migrations.DeleteModel(
            name='StrategyApproval',
        ),
    ]
