# Generated by Django 5.2.12 on 2026-10-06 13:31

from django.conf import settings
from django.db import migrations, models


def remove_retired_activity(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    AuditLog.objects.using(schema_editor.connection.alias).exclude(entity_type__in=[
        'Strategy', 'BrokerCredential', 'PaperAccount', 'CapitalAllocation',
        'LiveStrategyAllocation', 'PaperTradingSession', 'TradingSession', 'User',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_compliancecheck_strategy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_retired_activity),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('Strategy', 'Strategy'), ('BrokerCredential', 'Broker account'), ('PaperAccount', 'Paper account'), ('CapitalAllocation', 'Paper allocation'), ('LiveStrategyAllocation', 'Live allocation'), ('PaperTradingSession', 'Paper session'), ('TradingSession', 'Live session'), ('User', 'Authentication')], max_length=80),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.CheckConstraint(condition=models.Q(('entity_type__in', ['Strategy', 'BrokerCredential', 'PaperAccount', 'CapitalAllocation', 'LiveStrategyAllocation', 'PaperTradingSession', 'TradingSession', 'User'])), name='audit_supported_resource'),
        ),
    ]
